// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: jumpstart/domain/inframanager/v1/workflows.proto
// Protobuf Java Version: 4.28.3

package io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1;

/**
 * Protobuf type {@code
 * jumpstart.domain.inframanager.workflows.v1.GetInfraSpaceExecutionOptionsRequest}
 */
public final class GetInfraSpaceExecutionOptionsRequest extends com.google.protobuf.GeneratedMessage
    implements
    // @@protoc_insertion_point(message_implements:jumpstart.domain.inframanager.workflows.v1.GetInfraSpaceExecutionOptionsRequest)
    GetInfraSpaceExecutionOptionsRequestOrBuilder {
  private static final long serialVersionUID = 0L;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        GetInfraSpaceExecutionOptionsRequest.class.getName());
  }
  // Use GetInfraSpaceExecutionOptionsRequest.newBuilder() to construct.
  private GetInfraSpaceExecutionOptionsRequest(
      com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }

  private GetInfraSpaceExecutionOptionsRequest() {}

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
        .WorkflowsProto
        .internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceExecutionOptionsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
        .WorkflowsProto
        .internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceExecutionOptionsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .GetInfraSpaceExecutionOptionsRequest.class,
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .GetInfraSpaceExecutionOptionsRequest.Builder.class);
  }

  private int bitField0_;
  public static final int ARGS_FIELD_NUMBER = 1;
  private io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .InfraSpaceExecutionOptions
      args_;
  /**
   * <code>
   * optional .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions args = 1 [json_name = "args"];
   * </code>
   *
   * @return Whether the args field is set.
   */
  @java.lang.Override
  public boolean hasArgs() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>
   * optional .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions args = 1 [json_name = "args"];
   * </code>
   *
   * @return The args.
   */
  @java.lang.Override
  public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .InfraSpaceExecutionOptions
      getArgs() {
    return args_ == null
        ? io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .InfraSpaceExecutionOptions.getDefaultInstance()
        : args_;
  }
  /**
   * <code>
   * optional .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions args = 1 [json_name = "args"];
   * </code>
   */
  @java.lang.Override
  public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .InfraSpaceExecutionOptionsOrBuilder
      getArgsOrBuilder() {
    return args_ == null
        ? io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .InfraSpaceExecutionOptions.getDefaultInstance()
        : args_;
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getArgs());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getArgs());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj
        instanceof
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .GetInfraSpaceExecutionOptionsRequest)) {
      return super.equals(obj);
    }
    io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .GetInfraSpaceExecutionOptionsRequest
        other =
            (io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                    .GetInfraSpaceExecutionOptionsRequest)
                obj;

    if (hasArgs() != other.hasArgs()) return false;
    if (hasArgs()) {
      if (!getArgs().equals(other.getArgs())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasArgs()) {
      hash = (37 * hash) + ARGS_FIELD_NUMBER;
      hash = (53 * hash) + getArgs().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsRequest
      parseFrom(java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsRequest
      parseFrom(
          java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsRequest
      parseFrom(com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsRequest
      parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsRequest
      parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsRequest
      parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsRequest
      parseFrom(java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsRequest
      parseFrom(
          java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsRequest
      parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsRequest
      parseDelimitedFrom(
          java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsRequest
      parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsRequest
      parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(
      io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
              .GetInfraSpaceExecutionOptionsRequest
          prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code
   * jumpstart.domain.inframanager.workflows.v1.GetInfraSpaceExecutionOptionsRequest}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:jumpstart.domain.inframanager.workflows.v1.GetInfraSpaceExecutionOptionsRequest)
      io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .WorkflowsProto
          .internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceExecutionOptionsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .WorkflowsProto
          .internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceExecutionOptionsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                  .GetInfraSpaceExecutionOptionsRequest.class,
              io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                  .GetInfraSpaceExecutionOptionsRequest.Builder.class);
    }

    // Construct using
    // io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1.GetInfraSpaceExecutionOptionsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getArgsFieldBuilder();
      }
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      args_ = null;
      if (argsBuilder_ != null) {
        argsBuilder_.dispose();
        argsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .WorkflowsProto
          .internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceExecutionOptionsRequest_descriptor;
    }

    @java.lang.Override
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .GetInfraSpaceExecutionOptionsRequest
        getDefaultInstanceForType() {
      return io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .GetInfraSpaceExecutionOptionsRequest
        build() {
      io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
              .GetInfraSpaceExecutionOptionsRequest
          result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .GetInfraSpaceExecutionOptionsRequest
        buildPartial() {
      io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
              .GetInfraSpaceExecutionOptionsRequest
          result =
              new io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                  .GetInfraSpaceExecutionOptionsRequest(this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartial0(
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .GetInfraSpaceExecutionOptionsRequest
            result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.args_ = argsBuilder_ == null ? args_ : argsBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other
          instanceof
          io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
              .GetInfraSpaceExecutionOptionsRequest) {
        return mergeFrom(
            (io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                    .GetInfraSpaceExecutionOptionsRequest)
                other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .GetInfraSpaceExecutionOptionsRequest
            other) {
      if (other
          == io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
              .GetInfraSpaceExecutionOptionsRequest.getDefaultInstance()) return this;
      if (other.hasArgs()) {
        mergeArgs(other.getArgs());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                input.readMessage(getArgsFieldBuilder().getBuilder(), extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
            default:
              {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int bitField0_;

    private io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .InfraSpaceExecutionOptions
        args_;
    private com.google.protobuf.SingleFieldBuilder<
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions,
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions.Builder,
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptionsOrBuilder>
        argsBuilder_;
    /**
     * <code>
     * optional .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions args = 1 [json_name = "args"];
     * </code>
     *
     * @return Whether the args field is set.
     */
    public boolean hasArgs() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>
     * optional .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions args = 1 [json_name = "args"];
     * </code>
     *
     * @return The args.
     */
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .InfraSpaceExecutionOptions
        getArgs() {
      if (argsBuilder_ == null) {
        return args_ == null
            ? io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions.getDefaultInstance()
            : args_;
      } else {
        return argsBuilder_.getMessage();
      }
    }
    /**
     * <code>
     * optional .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions args = 1 [json_name = "args"];
     * </code>
     */
    public Builder setArgs(
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions
            value) {
      if (argsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        args_ = value;
      } else {
        argsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>
     * optional .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions args = 1 [json_name = "args"];
     * </code>
     */
    public Builder setArgs(
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions.Builder
            builderForValue) {
      if (argsBuilder_ == null) {
        args_ = builderForValue.build();
      } else {
        argsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>
     * optional .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions args = 1 [json_name = "args"];
     * </code>
     */
    public Builder mergeArgs(
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions
            value) {
      if (argsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)
            && args_ != null
            && args_
                != io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                    .InfraSpaceExecutionOptions.getDefaultInstance()) {
          getArgsBuilder().mergeFrom(value);
        } else {
          args_ = value;
        }
      } else {
        argsBuilder_.mergeFrom(value);
      }
      if (args_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>
     * optional .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions args = 1 [json_name = "args"];
     * </code>
     */
    public Builder clearArgs() {
      bitField0_ = (bitField0_ & ~0x00000001);
      args_ = null;
      if (argsBuilder_ != null) {
        argsBuilder_.dispose();
        argsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>
     * optional .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions args = 1 [json_name = "args"];
     * </code>
     */
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .InfraSpaceExecutionOptions.Builder
        getArgsBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getArgsFieldBuilder().getBuilder();
    }
    /**
     * <code>
     * optional .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions args = 1 [json_name = "args"];
     * </code>
     */
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .InfraSpaceExecutionOptionsOrBuilder
        getArgsOrBuilder() {
      if (argsBuilder_ != null) {
        return argsBuilder_.getMessageOrBuilder();
      } else {
        return args_ == null
            ? io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions.getDefaultInstance()
            : args_;
      }
    }
    /**
     * <code>
     * optional .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions args = 1 [json_name = "args"];
     * </code>
     */
    private com.google.protobuf.SingleFieldBuilder<
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions,
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions.Builder,
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptionsOrBuilder>
        getArgsFieldBuilder() {
      if (argsBuilder_ == null) {
        argsBuilder_ =
            new com.google.protobuf.SingleFieldBuilder<
                io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                    .InfraSpaceExecutionOptions,
                io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                    .InfraSpaceExecutionOptions.Builder,
                io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                    .InfraSpaceExecutionOptionsOrBuilder>(
                getArgs(), getParentForChildren(), isClean());
        args_ = null;
      }
      return argsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:jumpstart.domain.inframanager.workflows.v1.GetInfraSpaceExecutionOptionsRequest)
  }

  // @@protoc_insertion_point(class_scope:jumpstart.domain.inframanager.workflows.v1.GetInfraSpaceExecutionOptionsRequest)
  private static final io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsRequest
      DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE =
        new io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .GetInfraSpaceExecutionOptionsRequest();
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsRequest
      getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetInfraSpaceExecutionOptionsRequest> PARSER =
      new com.google.protobuf.AbstractParser<GetInfraSpaceExecutionOptionsRequest>() {
        @java.lang.Override
        public GetInfraSpaceExecutionOptionsRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

  public static com.google.protobuf.Parser<GetInfraSpaceExecutionOptionsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetInfraSpaceExecutionOptionsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsRequest
      getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
