// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: jumpstart/domain/inframanager/v1/workflows.proto
// Protobuf Java Version: 4.28.3

package io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1;

public interface GetInfraSpaceExecutionOptionsResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:jumpstart.domain.inframanager.workflows.v1.GetInfraSpaceExecutionOptionsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>
   * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 1 [json_name = "options"];
   * </code>
   *
   * @return Whether the options field is set.
   */
  boolean hasOptions();
  /**
   * <code>
   * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 1 [json_name = "options"];
   * </code>
   *
   * @return The options.
   */
  io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .InfraSpaceExecutionOptions
      getOptions();
  /**
   * <code>
   * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 1 [json_name = "options"];
   * </code>
   */
  io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .InfraSpaceExecutionOptionsOrBuilder
      getOptionsOrBuilder();
}
