// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: jumpstart/domain/inframanager/v1/workflows.proto
// Protobuf Java Version: 4.28.3

package io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1;

public interface GetInfraSpaceStateRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:jumpstart.domain.inframanager.workflows.v1.GetInfraSpaceStateRequest)
    com.google.protobuf.MessageOrBuilder {}
