// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: jumpstart/domain/inframanager/v1/workflows.proto
// Protobuf Java Version: 4.28.3

package io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1;

/**
 * Protobuf type {@code
 * jumpstart.domain.inframanager.workflows.v1.GetInfraSpaceExecutionOptionsResponse}
 */
public final class GetInfraSpaceExecutionOptionsResponse
    extends com.google.protobuf.GeneratedMessage
    implements
    // @@protoc_insertion_point(message_implements:jumpstart.domain.inframanager.workflows.v1.GetInfraSpaceExecutionOptionsResponse)
    GetInfraSpaceExecutionOptionsResponseOrBuilder {
  private static final long serialVersionUID = 0L;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        GetInfraSpaceExecutionOptionsResponse.class.getName());
  }
  // Use GetInfraSpaceExecutionOptionsResponse.newBuilder() to construct.
  private GetInfraSpaceExecutionOptionsResponse(
      com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }

  private GetInfraSpaceExecutionOptionsResponse() {}

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
        .WorkflowsProto
        .internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceExecutionOptionsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
        .WorkflowsProto
        .internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceExecutionOptionsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .GetInfraSpaceExecutionOptionsResponse.class,
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .GetInfraSpaceExecutionOptionsResponse.Builder.class);
  }

  private int bitField0_;
  public static final int OPTIONS_FIELD_NUMBER = 1;
  private io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .InfraSpaceExecutionOptions
      options_;
  /**
   * <code>
   * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 1 [json_name = "options"];
   * </code>
   *
   * @return Whether the options field is set.
   */
  @java.lang.Override
  public boolean hasOptions() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>
   * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 1 [json_name = "options"];
   * </code>
   *
   * @return The options.
   */
  @java.lang.Override
  public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .InfraSpaceExecutionOptions
      getOptions() {
    return options_ == null
        ? io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .InfraSpaceExecutionOptions.getDefaultInstance()
        : options_;
  }
  /**
   * <code>
   * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 1 [json_name = "options"];
   * </code>
   */
  @java.lang.Override
  public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .InfraSpaceExecutionOptionsOrBuilder
      getOptionsOrBuilder() {
    return options_ == null
        ? io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .InfraSpaceExecutionOptions.getDefaultInstance()
        : options_;
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getOptions());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getOptions());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj
        instanceof
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .GetInfraSpaceExecutionOptionsResponse)) {
      return super.equals(obj);
    }
    io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .GetInfraSpaceExecutionOptionsResponse
        other =
            (io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                    .GetInfraSpaceExecutionOptionsResponse)
                obj;

    if (hasOptions() != other.hasOptions()) return false;
    if (hasOptions()) {
      if (!getOptions().equals(other.getOptions())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasOptions()) {
      hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOptions().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsResponse
      parseFrom(java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsResponse
      parseFrom(
          java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsResponse
      parseFrom(com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsResponse
      parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsResponse
      parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsResponse
      parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsResponse
      parseFrom(java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsResponse
      parseFrom(
          java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsResponse
      parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsResponse
      parseDelimitedFrom(
          java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsResponse
      parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsResponse
      parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(
      io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
              .GetInfraSpaceExecutionOptionsResponse
          prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code
   * jumpstart.domain.inframanager.workflows.v1.GetInfraSpaceExecutionOptionsResponse}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:jumpstart.domain.inframanager.workflows.v1.GetInfraSpaceExecutionOptionsResponse)
      io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .WorkflowsProto
          .internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceExecutionOptionsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .WorkflowsProto
          .internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceExecutionOptionsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                  .GetInfraSpaceExecutionOptionsResponse.class,
              io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                  .GetInfraSpaceExecutionOptionsResponse.Builder.class);
    }

    // Construct using
    // io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1.GetInfraSpaceExecutionOptionsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getOptionsFieldBuilder();
      }
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      options_ = null;
      if (optionsBuilder_ != null) {
        optionsBuilder_.dispose();
        optionsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .WorkflowsProto
          .internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceExecutionOptionsResponse_descriptor;
    }

    @java.lang.Override
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .GetInfraSpaceExecutionOptionsResponse
        getDefaultInstanceForType() {
      return io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .GetInfraSpaceExecutionOptionsResponse
        build() {
      io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
              .GetInfraSpaceExecutionOptionsResponse
          result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .GetInfraSpaceExecutionOptionsResponse
        buildPartial() {
      io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
              .GetInfraSpaceExecutionOptionsResponse
          result =
              new io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                  .GetInfraSpaceExecutionOptionsResponse(this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartial0(
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .GetInfraSpaceExecutionOptionsResponse
            result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.options_ = optionsBuilder_ == null ? options_ : optionsBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other
          instanceof
          io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
              .GetInfraSpaceExecutionOptionsResponse) {
        return mergeFrom(
            (io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                    .GetInfraSpaceExecutionOptionsResponse)
                other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .GetInfraSpaceExecutionOptionsResponse
            other) {
      if (other
          == io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
              .GetInfraSpaceExecutionOptionsResponse.getDefaultInstance()) return this;
      if (other.hasOptions()) {
        mergeOptions(other.getOptions());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                input.readMessage(getOptionsFieldBuilder().getBuilder(), extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
            default:
              {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int bitField0_;

    private io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .InfraSpaceExecutionOptions
        options_;
    private com.google.protobuf.SingleFieldBuilder<
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions,
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions.Builder,
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptionsOrBuilder>
        optionsBuilder_;
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 1 [json_name = "options"];
     * </code>
     *
     * @return Whether the options field is set.
     */
    public boolean hasOptions() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 1 [json_name = "options"];
     * </code>
     *
     * @return The options.
     */
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .InfraSpaceExecutionOptions
        getOptions() {
      if (optionsBuilder_ == null) {
        return options_ == null
            ? io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions.getDefaultInstance()
            : options_;
      } else {
        return optionsBuilder_.getMessage();
      }
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 1 [json_name = "options"];
     * </code>
     */
    public Builder setOptions(
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions
            value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        options_ = value;
      } else {
        optionsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 1 [json_name = "options"];
     * </code>
     */
    public Builder setOptions(
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions.Builder
            builderForValue) {
      if (optionsBuilder_ == null) {
        options_ = builderForValue.build();
      } else {
        optionsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 1 [json_name = "options"];
     * </code>
     */
    public Builder mergeOptions(
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions
            value) {
      if (optionsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)
            && options_ != null
            && options_
                != io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                    .InfraSpaceExecutionOptions.getDefaultInstance()) {
          getOptionsBuilder().mergeFrom(value);
        } else {
          options_ = value;
        }
      } else {
        optionsBuilder_.mergeFrom(value);
      }
      if (options_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 1 [json_name = "options"];
     * </code>
     */
    public Builder clearOptions() {
      bitField0_ = (bitField0_ & ~0x00000001);
      options_ = null;
      if (optionsBuilder_ != null) {
        optionsBuilder_.dispose();
        optionsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 1 [json_name = "options"];
     * </code>
     */
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .InfraSpaceExecutionOptions.Builder
        getOptionsBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getOptionsFieldBuilder().getBuilder();
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 1 [json_name = "options"];
     * </code>
     */
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .InfraSpaceExecutionOptionsOrBuilder
        getOptionsOrBuilder() {
      if (optionsBuilder_ != null) {
        return optionsBuilder_.getMessageOrBuilder();
      } else {
        return options_ == null
            ? io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions.getDefaultInstance()
            : options_;
      }
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 1 [json_name = "options"];
     * </code>
     */
    private com.google.protobuf.SingleFieldBuilder<
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions,
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions.Builder,
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptionsOrBuilder>
        getOptionsFieldBuilder() {
      if (optionsBuilder_ == null) {
        optionsBuilder_ =
            new com.google.protobuf.SingleFieldBuilder<
                io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                    .InfraSpaceExecutionOptions,
                io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                    .InfraSpaceExecutionOptions.Builder,
                io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                    .InfraSpaceExecutionOptionsOrBuilder>(
                getOptions(), getParentForChildren(), isClean());
        options_ = null;
      }
      return optionsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:jumpstart.domain.inframanager.workflows.v1.GetInfraSpaceExecutionOptionsResponse)
  }

  // @@protoc_insertion_point(class_scope:jumpstart.domain.inframanager.workflows.v1.GetInfraSpaceExecutionOptionsResponse)
  private static final io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsResponse
      DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE =
        new io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .GetInfraSpaceExecutionOptionsResponse();
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsResponse
      getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetInfraSpaceExecutionOptionsResponse> PARSER =
      new com.google.protobuf.AbstractParser<GetInfraSpaceExecutionOptionsResponse>() {
        @java.lang.Override
        public GetInfraSpaceExecutionOptionsResponse parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

  public static com.google.protobuf.Parser<GetInfraSpaceExecutionOptionsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetInfraSpaceExecutionOptionsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceExecutionOptionsResponse
      getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
