// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: jumpstart/domain/inframanager/v1/workflows.proto
// Protobuf Java Version: 4.28.3

package io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1;

/** Protobuf type {@code jumpstart.domain.inframanager.workflows.v1.GetInfraSpaceStateResponse} */
public final class GetInfraSpaceStateResponse extends com.google.protobuf.GeneratedMessage
    implements
    // @@protoc_insertion_point(message_implements:jumpstart.domain.inframanager.workflows.v1.GetInfraSpaceStateResponse)
    GetInfraSpaceStateResponseOrBuilder {
  private static final long serialVersionUID = 0L;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        GetInfraSpaceStateResponse.class.getName());
  }
  // Use GetInfraSpaceStateResponse.newBuilder() to construct.
  private GetInfraSpaceStateResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }

  private GetInfraSpaceStateResponse() {
    name_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
        .WorkflowsProto
        .internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceStateResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
        .WorkflowsProto
        .internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceStateResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .GetInfraSpaceStateResponse.class,
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .GetInfraSpaceStateResponse.Builder.class);
  }

  private int bitField0_;
  public static final int ARGS_FIELD_NUMBER = 1;
  private io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .StartInfraSpaceRequest
      args_;
  /**
   * <code>
   * .jumpstart.domain.inframanager.workflows.v1.StartInfraSpaceRequest args = 1 [json_name = "args"];
   * </code>
   *
   * @return Whether the args field is set.
   */
  @java.lang.Override
  public boolean hasArgs() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>
   * .jumpstart.domain.inframanager.workflows.v1.StartInfraSpaceRequest args = 1 [json_name = "args"];
   * </code>
   *
   * @return The args.
   */
  @java.lang.Override
  public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .StartInfraSpaceRequest
      getArgs() {
    return args_ == null
        ? io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .StartInfraSpaceRequest.getDefaultInstance()
        : args_;
  }
  /**
   * <code>
   * .jumpstart.domain.inframanager.workflows.v1.StartInfraSpaceRequest args = 1 [json_name = "args"];
   * </code>
   */
  @java.lang.Override
  public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .StartInfraSpaceRequestOrBuilder
      getArgsOrBuilder() {
    return args_ == null
        ? io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .StartInfraSpaceRequest.getDefaultInstance()
        : args_;
  }

  public static final int OPTIONS_FIELD_NUMBER = 2;
  private io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .InfraSpaceExecutionOptions
      options_;
  /**
   * <code>
   * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 2 [json_name = "options"];
   * </code>
   *
   * @return Whether the options field is set.
   */
  @java.lang.Override
  public boolean hasOptions() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>
   * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 2 [json_name = "options"];
   * </code>
   *
   * @return The options.
   */
  @java.lang.Override
  public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .InfraSpaceExecutionOptions
      getOptions() {
    return options_ == null
        ? io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .InfraSpaceExecutionOptions.getDefaultInstance()
        : options_;
  }
  /**
   * <code>
   * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 2 [json_name = "options"];
   * </code>
   */
  @java.lang.Override
  public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .InfraSpaceExecutionOptionsOrBuilder
      getOptionsOrBuilder() {
    return options_ == null
        ? io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .InfraSpaceExecutionOptions.getDefaultInstance()
        : options_;
  }

  public static final int NAME_FIELD_NUMBER = 3;

  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 3 [json_name = "name"];</code>
   *
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 3 [json_name = "name"];</code>
   *
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getArgs());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getOptions());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, name_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getArgs());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, getOptions());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, name_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj
        instanceof
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .GetInfraSpaceStateResponse)) {
      return super.equals(obj);
    }
    io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .GetInfraSpaceStateResponse
        other =
            (io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                    .GetInfraSpaceStateResponse)
                obj;

    if (hasArgs() != other.hasArgs()) return false;
    if (hasArgs()) {
      if (!getArgs().equals(other.getArgs())) return false;
    }
    if (hasOptions() != other.hasOptions()) return false;
    if (hasOptions()) {
      if (!getOptions().equals(other.getOptions())) return false;
    }
    if (!getName().equals(other.getName())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasArgs()) {
      hash = (37 * hash) + ARGS_FIELD_NUMBER;
      hash = (53 * hash) + getArgs().hashCode();
    }
    if (hasOptions()) {
      hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOptions().hashCode();
    }
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceStateResponse
      parseFrom(java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceStateResponse
      parseFrom(
          java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceStateResponse
      parseFrom(com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceStateResponse
      parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceStateResponse
      parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceStateResponse
      parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceStateResponse
      parseFrom(java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceStateResponse
      parseFrom(
          java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceStateResponse
      parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceStateResponse
      parseDelimitedFrom(
          java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceStateResponse
      parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceStateResponse
      parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(
      io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
              .GetInfraSpaceStateResponse
          prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /** Protobuf type {@code jumpstart.domain.inframanager.workflows.v1.GetInfraSpaceStateResponse} */
  public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:jumpstart.domain.inframanager.workflows.v1.GetInfraSpaceStateResponse)
      io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceStateResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .WorkflowsProto
          .internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceStateResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .WorkflowsProto
          .internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceStateResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                  .GetInfraSpaceStateResponse.class,
              io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                  .GetInfraSpaceStateResponse.Builder.class);
    }

    // Construct using
    // io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1.GetInfraSpaceStateResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getArgsFieldBuilder();
        getOptionsFieldBuilder();
      }
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      args_ = null;
      if (argsBuilder_ != null) {
        argsBuilder_.dispose();
        argsBuilder_ = null;
      }
      options_ = null;
      if (optionsBuilder_ != null) {
        optionsBuilder_.dispose();
        optionsBuilder_ = null;
      }
      name_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .WorkflowsProto
          .internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceStateResponse_descriptor;
    }

    @java.lang.Override
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .GetInfraSpaceStateResponse
        getDefaultInstanceForType() {
      return io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceStateResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .GetInfraSpaceStateResponse
        build() {
      io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
              .GetInfraSpaceStateResponse
          result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .GetInfraSpaceStateResponse
        buildPartial() {
      io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
              .GetInfraSpaceStateResponse
          result =
              new io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                  .GetInfraSpaceStateResponse(this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartial0(
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .GetInfraSpaceStateResponse
            result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.args_ = argsBuilder_ == null ? args_ : argsBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.options_ = optionsBuilder_ == null ? options_ : optionsBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.name_ = name_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other
          instanceof
          io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
              .GetInfraSpaceStateResponse) {
        return mergeFrom(
            (io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                    .GetInfraSpaceStateResponse)
                other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .GetInfraSpaceStateResponse
            other) {
      if (other
          == io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
              .GetInfraSpaceStateResponse.getDefaultInstance()) return this;
      if (other.hasArgs()) {
        mergeArgs(other.getArgs());
      }
      if (other.hasOptions()) {
        mergeOptions(other.getOptions());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                input.readMessage(getArgsFieldBuilder().getBuilder(), extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
            case 18:
              {
                input.readMessage(getOptionsFieldBuilder().getBuilder(), extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
            case 26:
              {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
            default:
              {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int bitField0_;

    private io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .StartInfraSpaceRequest
        args_;
    private com.google.protobuf.SingleFieldBuilder<
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .StartInfraSpaceRequest,
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .StartInfraSpaceRequest.Builder,
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .StartInfraSpaceRequestOrBuilder>
        argsBuilder_;
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.StartInfraSpaceRequest args = 1 [json_name = "args"];
     * </code>
     *
     * @return Whether the args field is set.
     */
    public boolean hasArgs() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.StartInfraSpaceRequest args = 1 [json_name = "args"];
     * </code>
     *
     * @return The args.
     */
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .StartInfraSpaceRequest
        getArgs() {
      if (argsBuilder_ == null) {
        return args_ == null
            ? io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .StartInfraSpaceRequest.getDefaultInstance()
            : args_;
      } else {
        return argsBuilder_.getMessage();
      }
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.StartInfraSpaceRequest args = 1 [json_name = "args"];
     * </code>
     */
    public Builder setArgs(
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .StartInfraSpaceRequest
            value) {
      if (argsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        args_ = value;
      } else {
        argsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.StartInfraSpaceRequest args = 1 [json_name = "args"];
     * </code>
     */
    public Builder setArgs(
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .StartInfraSpaceRequest.Builder
            builderForValue) {
      if (argsBuilder_ == null) {
        args_ = builderForValue.build();
      } else {
        argsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.StartInfraSpaceRequest args = 1 [json_name = "args"];
     * </code>
     */
    public Builder mergeArgs(
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .StartInfraSpaceRequest
            value) {
      if (argsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)
            && args_ != null
            && args_
                != io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                    .StartInfraSpaceRequest.getDefaultInstance()) {
          getArgsBuilder().mergeFrom(value);
        } else {
          args_ = value;
        }
      } else {
        argsBuilder_.mergeFrom(value);
      }
      if (args_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.StartInfraSpaceRequest args = 1 [json_name = "args"];
     * </code>
     */
    public Builder clearArgs() {
      bitField0_ = (bitField0_ & ~0x00000001);
      args_ = null;
      if (argsBuilder_ != null) {
        argsBuilder_.dispose();
        argsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.StartInfraSpaceRequest args = 1 [json_name = "args"];
     * </code>
     */
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .StartInfraSpaceRequest.Builder
        getArgsBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getArgsFieldBuilder().getBuilder();
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.StartInfraSpaceRequest args = 1 [json_name = "args"];
     * </code>
     */
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .StartInfraSpaceRequestOrBuilder
        getArgsOrBuilder() {
      if (argsBuilder_ != null) {
        return argsBuilder_.getMessageOrBuilder();
      } else {
        return args_ == null
            ? io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .StartInfraSpaceRequest.getDefaultInstance()
            : args_;
      }
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.StartInfraSpaceRequest args = 1 [json_name = "args"];
     * </code>
     */
    private com.google.protobuf.SingleFieldBuilder<
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .StartInfraSpaceRequest,
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .StartInfraSpaceRequest.Builder,
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .StartInfraSpaceRequestOrBuilder>
        getArgsFieldBuilder() {
      if (argsBuilder_ == null) {
        argsBuilder_ =
            new com.google.protobuf.SingleFieldBuilder<
                io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                    .StartInfraSpaceRequest,
                io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                    .StartInfraSpaceRequest.Builder,
                io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                    .StartInfraSpaceRequestOrBuilder>(getArgs(), getParentForChildren(), isClean());
        args_ = null;
      }
      return argsBuilder_;
    }

    private io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .InfraSpaceExecutionOptions
        options_;
    private com.google.protobuf.SingleFieldBuilder<
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions,
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions.Builder,
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptionsOrBuilder>
        optionsBuilder_;
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 2 [json_name = "options"];
     * </code>
     *
     * @return Whether the options field is set.
     */
    public boolean hasOptions() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 2 [json_name = "options"];
     * </code>
     *
     * @return The options.
     */
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .InfraSpaceExecutionOptions
        getOptions() {
      if (optionsBuilder_ == null) {
        return options_ == null
            ? io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions.getDefaultInstance()
            : options_;
      } else {
        return optionsBuilder_.getMessage();
      }
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 2 [json_name = "options"];
     * </code>
     */
    public Builder setOptions(
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions
            value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        options_ = value;
      } else {
        optionsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 2 [json_name = "options"];
     * </code>
     */
    public Builder setOptions(
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions.Builder
            builderForValue) {
      if (optionsBuilder_ == null) {
        options_ = builderForValue.build();
      } else {
        optionsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 2 [json_name = "options"];
     * </code>
     */
    public Builder mergeOptions(
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions
            value) {
      if (optionsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)
            && options_ != null
            && options_
                != io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                    .InfraSpaceExecutionOptions.getDefaultInstance()) {
          getOptionsBuilder().mergeFrom(value);
        } else {
          options_ = value;
        }
      } else {
        optionsBuilder_.mergeFrom(value);
      }
      if (options_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 2 [json_name = "options"];
     * </code>
     */
    public Builder clearOptions() {
      bitField0_ = (bitField0_ & ~0x00000002);
      options_ = null;
      if (optionsBuilder_ != null) {
        optionsBuilder_.dispose();
        optionsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 2 [json_name = "options"];
     * </code>
     */
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .InfraSpaceExecutionOptions.Builder
        getOptionsBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getOptionsFieldBuilder().getBuilder();
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 2 [json_name = "options"];
     * </code>
     */
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .InfraSpaceExecutionOptionsOrBuilder
        getOptionsOrBuilder() {
      if (optionsBuilder_ != null) {
        return optionsBuilder_.getMessageOrBuilder();
      } else {
        return options_ == null
            ? io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions.getDefaultInstance()
            : options_;
      }
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 2 [json_name = "options"];
     * </code>
     */
    private com.google.protobuf.SingleFieldBuilder<
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions,
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptions.Builder,
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                .InfraSpaceExecutionOptionsOrBuilder>
        getOptionsFieldBuilder() {
      if (optionsBuilder_ == null) {
        optionsBuilder_ =
            new com.google.protobuf.SingleFieldBuilder<
                io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                    .InfraSpaceExecutionOptions,
                io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                    .InfraSpaceExecutionOptions.Builder,
                io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
                    .InfraSpaceExecutionOptionsOrBuilder>(
                getOptions(), getParentForChildren(), isClean());
        options_ = null;
      }
      return optionsBuilder_;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 3 [json_name = "name"];</code>
     *
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 3 [json_name = "name"];</code>
     *
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 3 [json_name = "name"];</code>
     *
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      name_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3 [json_name = "name"];</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3 [json_name = "name"];</code>
     *
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:jumpstart.domain.inframanager.workflows.v1.GetInfraSpaceStateResponse)
  }

  // @@protoc_insertion_point(class_scope:jumpstart.domain.inframanager.workflows.v1.GetInfraSpaceStateResponse)
  private static final io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceStateResponse
      DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE =
        new io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
            .GetInfraSpaceStateResponse();
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceStateResponse
      getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetInfraSpaceStateResponse> PARSER =
      new com.google.protobuf.AbstractParser<GetInfraSpaceStateResponse>() {
        @java.lang.Override
        public GetInfraSpaceStateResponse parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

  public static com.google.protobuf.Parser<GetInfraSpaceStateResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetInfraSpaceStateResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .GetInfraSpaceStateResponse
      getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
