// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: jumpstart/domain/inframanager/v1/workflows.proto
// Protobuf Java Version: 4.28.3

package io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1;

public interface StartInfraSpaceRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:jumpstart.domain.inframanager.workflows.v1.StartInfraSpaceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>
   * optional .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 1 [json_name = "options"];
   * </code>
   *
   * @return Whether the options field is set.
   */
  boolean hasOptions();
  /**
   * <code>
   * optional .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 1 [json_name = "options"];
   * </code>
   *
   * @return The options.
   */
  io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .InfraSpaceExecutionOptions
      getOptions();
  /**
   * <code>
   * optional .jumpstart.domain.inframanager.workflows.v1.InfraSpaceExecutionOptions options = 1 [json_name = "options"];
   * </code>
   */
  io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1
          .InfraSpaceExecutionOptionsOrBuilder
      getOptionsOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
   *
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
   *
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /** <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code> */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <code>string name = 4 [json_name = "name"];</code>
   *
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 4 [json_name = "name"];</code>
   *
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString getNameBytes();
}
