// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: jumpstart/domain/inframanager/v1/workflows.proto
// Protobuf Java Version: 4.28.3

package io.temporal.inframanager.messages.jumpstart.domain.inframanager.workflows.v1;

public final class WorkflowsProto {
  private WorkflowsProto() {}

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        WorkflowsProto.class.getName());
  }

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_jumpstart_domain_inframanager_workflows_v1_StartInfraSpaceRequest_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jumpstart_domain_inframanager_workflows_v1_StartInfraSpaceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_jumpstart_domain_inframanager_workflows_v1_InfraSpaceExecutionOptions_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jumpstart_domain_inframanager_workflows_v1_InfraSpaceExecutionOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceStateRequest_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceStateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceStateResponse_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceStateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceExecutionOptionsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceExecutionOptionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceExecutionOptionsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceExecutionOptionsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n0jumpstart/domain/inframanager/v1/workf"
          + "lows.proto\022*jumpstart.domain.inframanage"
          + "r.workflows.v1\032-jumpstart/domain/inframa"
          + "nager/v1/values.proto\032\037google/protobuf/t"
          + "imestamp.proto\"\331\001\n\026StartInfraSpaceReques"
          + "t\022e\n\007options\030\001 \001(\0132F.jumpstart.domain.in"
          + "framanager.workflows.v1.InfraSpaceExecut"
          + "ionOptionsH\000R\007options\210\001\001\0228\n\ttimestamp\030\002 "
          + "\001(\0132\032.google.protobuf.TimestampR\ttimesta"
          + "mp\022\022\n\004name\030\004 \001(\tR\004nameB\n\n\010_options\"\034\n\032In"
          + "fraSpaceExecutionOptions\"\033\n\031GetInfraSpac"
          + "eStateRequest\"\352\001\n\032GetInfraSpaceStateResp"
          + "onse\022V\n\004args\030\001 \001(\0132B.jumpstart.domain.in"
          + "framanager.workflows.v1.StartInfraSpaceR"
          + "equestR\004args\022`\n\007options\030\002 \001(\0132F.jumpstar"
          + "t.domain.inframanager.workflows.v1.Infra"
          + "SpaceExecutionOptionsR\007options\022\022\n\004name\030\003"
          + " \001(\tR\004name\"\220\001\n$GetInfraSpaceExecutionOpt"
          + "ionsRequest\022_\n\004args\030\001 \001(\0132F.jumpstart.do"
          + "main.inframanager.workflows.v1.InfraSpac"
          + "eExecutionOptionsH\000R\004args\210\001\001B\007\n\005_args\"\211\001"
          + "\n%GetInfraSpaceExecutionOptionsResponse\022"
          + "`\n\007options\030\001 \001(\0132F.jumpstart.domain.infr"
          + "amanager.workflows.v1.InfraSpaceExecutio"
          + "nOptionsR\007optionsB\253\002\nLio.temporal.infram"
          + "anager.messages.jumpstart.domain.inframa"
          + "nager.workflows.v1B\016WorkflowsProtoP\001\242\002\004J"
          + "DIW\252\002*Jumpstart.Domain.Inframanager.Work"
          + "flows.V1\312\002*Jumpstart\\Domain\\Inframanager"
          + "\\Workflows\\V1\342\0026Jumpstart\\Domain\\Inframa"
          + "nager\\Workflows\\V1\\GPBMetadata\352\002.Jumpsta"
          + "rt::Domain::Inframanager::Workflows::V1b"
          + "\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.ValuesProto
                  .getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
            });
    internal_static_jumpstart_domain_inframanager_workflows_v1_StartInfraSpaceRequest_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_jumpstart_domain_inframanager_workflows_v1_StartInfraSpaceRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_jumpstart_domain_inframanager_workflows_v1_StartInfraSpaceRequest_descriptor,
            new java.lang.String[] {
              "Options", "Timestamp", "Name",
            });
    internal_static_jumpstart_domain_inframanager_workflows_v1_InfraSpaceExecutionOptions_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_jumpstart_domain_inframanager_workflows_v1_InfraSpaceExecutionOptions_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_jumpstart_domain_inframanager_workflows_v1_InfraSpaceExecutionOptions_descriptor,
            new java.lang.String[] {});
    internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceStateRequest_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceStateRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceStateRequest_descriptor,
            new java.lang.String[] {});
    internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceStateResponse_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceStateResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceStateResponse_descriptor,
            new java.lang.String[] {
              "Args", "Options", "Name",
            });
    internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceExecutionOptionsRequest_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceExecutionOptionsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceExecutionOptionsRequest_descriptor,
            new java.lang.String[] {
              "Args",
            });
    internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceExecutionOptionsResponse_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceExecutionOptionsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_jumpstart_domain_inframanager_workflows_v1_GetInfraSpaceExecutionOptionsResponse_descriptor,
            new java.lang.String[] {
              "Options",
            });
    descriptor.resolveAllFeaturesImmutable();
    io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.ValuesProto
        .getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
