// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: applications/v1/commands.proto
// Protobuf Java Version: 4.31.1

package io.temporal.fsi.api.applications.v1;

@com.google.protobuf.Generated
public final class CommandsProto {
  private CommandsProto() {}

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        CommandsProto.class.getName());
  }

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_applications_v1_RegisterUserRequest_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_applications_v1_RegisterUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_applications_v1_RegisterUserResponse_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_applications_v1_RegisterUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_applications_v1_AuthorizeUserRequest_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_applications_v1_AuthorizeUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_applications_v1_AuthorizeUserResponse_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_applications_v1_AuthorizeUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_applications_v1_ValidateEligibleRequest_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_applications_v1_ValidateEligibleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_applications_v1_ValidateEligibleResponse_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_applications_v1_ValidateEligibleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_applications_v1_MatchClientRequest_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_applications_v1_MatchClientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_applications_v1_MatchClientResponse_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_applications_v1_MatchClientResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_applications_v1_RequestExistingClientRequest_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_applications_v1_RequestExistingClientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_applications_v1_LinkExistingClientRequest_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_applications_v1_LinkExistingClientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_applications_v1_ForwardClientRequest_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_applications_v1_ForwardClientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_applications_v1_ForwardClientResponse_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_applications_v1_ForwardClientResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_applications_v1_ApplyWealthManagementVendorRequest_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_applications_v1_ApplyWealthManagementVendorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_applications_v1_ApplyWealthManagementVendorResponse_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_applications_v1_ApplyWealthManagementVendorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\036applications/v1/commands.proto\022\017applic"
          + "ations.v1\"Q\n\023RegisterUserRequest\022\016\n\002id\030\001"
          + " \001(\tR\002id\022\024\n\005email\030\002 \001(\tR\005email\022\024\n\005token\030"
          + "\003 \001(\tR\005token\"R\n\024RegisterUserResponse\022\016\n\002"
          + "id\030\001 \001(\tR\002id\022\024\n\005email\030\002 \001(\tR\005email\022\024\n\005to"
          + "ken\030\003 \001(\tR\005token\"V\n\024AuthorizeUserRequest"
          + "\022\024\n\005email\030\001 \001(\tR\005email\022\024\n\005token\030\002 \001(\tR\005t"
          + "oken\022\022\n\004code\030\003 \001(\tR\004code\"0\n\025AuthorizeUse"
          + "rResponse\022\027\n\007user_id\030\001 \001(\tR\006userId\"2\n\027Va"
          + "lidateEligibleRequest\022\027\n\007user_id\030\001 \001(\tR\006"
          + "userId\"\032\n\030ValidateEligibleResponse\"X\n\022Ma"
          + "tchClientRequest\022\020\n\003ssn\030\001 \001(\tR\003ssn\022\034\n\tbi"
          + "rthdate\030\002 \001(\tR\tbirthdate\022\022\n\004name\030\003 \001(\tR\004"
          + "name\"O\n\023MatchClientResponse\022\033\n\tclient_id"
          + "\030\001 \001(\tR\010clientId\022\033\n\tnot_found\030\002 \001(\010R\010not"
          + "Found\"{\n\034RequestExistingClientRequest\022\020\n"
          + "\003ssn\030\001 \001(\tR\003ssn\022\034\n\tbirthdate\030\002 \001(\tR\tbirt"
          + "hdate\022\022\n\004name\030\003 \001(\tR\004name\022\027\n\007user_id\030\004 \001"
          + "(\tR\006userId\"Q\n\031LinkExistingClientRequest\022"
          + "\027\n\007user_id\030\001 \001(\tR\006userId\022\033\n\tclient_id\030\002 "
          + "\001(\tR\010clientId\"L\n\024ForwardClientRequest\022\027\n"
          + "\007user_id\030\001 \001(\tR\006userId\022\033\n\tclient_id\030\002 \001("
          + "\tR\010clientId\"\027\n\025ForwardClientResponse\"Z\n\""
          + "ApplyWealthManagementVendorRequest\022\033\n\tcl"
          + "ient_id\030\001 \001(\tR\010clientId\022\027\n\007user_id\030\002 \001(\t"
          + "R\006userId\"B\n#ApplyWealthManagementVendorR"
          + "esponse\022\033\n\tclient_id\030\001 \001(\tR\010clientIdB\221\001\n"
          + "#io.temporal.fsi.api.applications.v1B\rCo"
          + "mmandsProtoP\001\242\002\003AXX\252\002\017Applications.V1\312\002\017"
          + "Applications\\V1\342\002\033Applications\\V1\\GPBMet"
          + "adata\352\002\020Applications::V1b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {});
    internal_static_applications_v1_RegisterUserRequest_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_applications_v1_RegisterUserRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_applications_v1_RegisterUserRequest_descriptor,
            new java.lang.String[] {
              "Id", "Email", "Token",
            });
    internal_static_applications_v1_RegisterUserResponse_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_applications_v1_RegisterUserResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_applications_v1_RegisterUserResponse_descriptor,
            new java.lang.String[] {
              "Id", "Email", "Token",
            });
    internal_static_applications_v1_AuthorizeUserRequest_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_applications_v1_AuthorizeUserRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_applications_v1_AuthorizeUserRequest_descriptor,
            new java.lang.String[] {
              "Email", "Token", "Code",
            });
    internal_static_applications_v1_AuthorizeUserResponse_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_applications_v1_AuthorizeUserResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_applications_v1_AuthorizeUserResponse_descriptor,
            new java.lang.String[] {
              "UserId",
            });
    internal_static_applications_v1_ValidateEligibleRequest_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_applications_v1_ValidateEligibleRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_applications_v1_ValidateEligibleRequest_descriptor,
            new java.lang.String[] {
              "UserId",
            });
    internal_static_applications_v1_ValidateEligibleResponse_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_applications_v1_ValidateEligibleResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_applications_v1_ValidateEligibleResponse_descriptor,
            new java.lang.String[] {});
    internal_static_applications_v1_MatchClientRequest_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_applications_v1_MatchClientRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_applications_v1_MatchClientRequest_descriptor,
            new java.lang.String[] {
              "Ssn", "Birthdate", "Name",
            });
    internal_static_applications_v1_MatchClientResponse_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_applications_v1_MatchClientResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_applications_v1_MatchClientResponse_descriptor,
            new java.lang.String[] {
              "ClientId", "NotFound",
            });
    internal_static_applications_v1_RequestExistingClientRequest_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_applications_v1_RequestExistingClientRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_applications_v1_RequestExistingClientRequest_descriptor,
            new java.lang.String[] {
              "Ssn", "Birthdate", "Name", "UserId",
            });
    internal_static_applications_v1_LinkExistingClientRequest_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_applications_v1_LinkExistingClientRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_applications_v1_LinkExistingClientRequest_descriptor,
            new java.lang.String[] {
              "UserId", "ClientId",
            });
    internal_static_applications_v1_ForwardClientRequest_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_applications_v1_ForwardClientRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_applications_v1_ForwardClientRequest_descriptor,
            new java.lang.String[] {
              "UserId", "ClientId",
            });
    internal_static_applications_v1_ForwardClientResponse_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_applications_v1_ForwardClientResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_applications_v1_ForwardClientResponse_descriptor,
            new java.lang.String[] {});
    internal_static_applications_v1_ApplyWealthManagementVendorRequest_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_applications_v1_ApplyWealthManagementVendorRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_applications_v1_ApplyWealthManagementVendorRequest_descriptor,
            new java.lang.String[] {
              "ClientId", "UserId",
            });
    internal_static_applications_v1_ApplyWealthManagementVendorResponse_descriptor =
        getDescriptor().getMessageTypes().get(13);
    internal_static_applications_v1_ApplyWealthManagementVendorResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_applications_v1_ApplyWealthManagementVendorResponse_descriptor,
            new java.lang.String[] {
              "ClientId",
            });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
