// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: applications/v1/commands.proto
// Protobuf Java Version: 4.31.1

package io.temporal.fsi.api.applications.v1;

@com.google.protobuf.Generated
public final class CommandsProto {
  private CommandsProto() {}

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        CommandsProto.class.getName());
  }

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_applications_v1_RegisterUserRequest_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_applications_v1_RegisterUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_applications_v1_RegisterUserResponse_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_applications_v1_RegisterUserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\036applications/v1/commands.proto\022\017applic"
          + "ations.v1\"+\n\023RegisterUserRequest\022\024\n\005emai"
          + "l\030\001 \001(\tR\005email\"B\n\024RegisterUserResponse\022\024"
          + "\n\005email\030\001 \001(\tR\005email\022\024\n\005token\030\002 \001(\tR\005tok"
          + "enB\221\001\n#io.temporal.fsi.api.applications."
          + "v1B\rCommandsProtoP\001\242\002\003AXX\252\002\017Applications"
          + ".V1\312\002\017Applications\\V1\342\002\033Applications\\V1\\"
          + "GPBMetadata\352\002\020Applications::V1b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {});
    internal_static_applications_v1_RegisterUserRequest_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_applications_v1_RegisterUserRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_applications_v1_RegisterUserRequest_descriptor,
            new java.lang.String[] {
              "Email",
            });
    internal_static_applications_v1_RegisterUserResponse_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_applications_v1_RegisterUserResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_applications_v1_RegisterUserResponse_descriptor,
            new java.lang.String[] {
              "Email", "Token",
            });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
