// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: applications/v1/commands.proto
// Protobuf Java Version: 4.31.1

package io.temporal.fsi.api.applications.v1;

@com.google.protobuf.Generated
public interface ForwardClientResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:applications.v1.ForwardClientResponse)
    com.google.protobuf.MessageOrBuilder {}
