// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: applications/v1/queries.proto
// Protobuf Java Version: 4.31.1

package io.temporal.fsi.api.applications.v1;

@com.google.protobuf.Generated
public interface GetApplicationResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:applications.v1.GetApplicationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.applications.v1.StartApplicationRequest args = 1 [json_name = "args"];</code>
   *
   * @return Whether the args field is set.
   */
  boolean hasArgs();
  /**
   * <code>.applications.v1.StartApplicationRequest args = 1 [json_name = "args"];</code>
   *
   * @return The args.
   */
  io.temporal.fsi.api.applications.v1.StartApplicationRequest getArgs();
  /** <code>.applications.v1.StartApplicationRequest args = 1 [json_name = "args"];</code> */
  io.temporal.fsi.api.applications.v1.StartApplicationRequestOrBuilder getArgsOrBuilder();

  /**
   * <code>string user_id = 2 [json_name = "userId"];</code>
   *
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 2 [json_name = "userId"];</code>
   *
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString getUserIdBytes();

  /**
   * <code>string name = 3 [json_name = "name"];</code>
   *
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3 [json_name = "name"];</code>
   *
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString getNameBytes();

  /**
   * <code>string client_id = 4 [json_name = "clientId"];</code>
   *
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <code>string client_id = 4 [json_name = "clientId"];</code>
   *
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString getClientIdBytes();
}
