// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: applications/v1/queries.proto
// Protobuf Java Version: 4.31.1

package io.temporal.fsi.api.applications.v1;

@com.google.protobuf.Generated
public interface GetUserRegistrationsResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:applications.v1.GetUserRegistrationsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>
   * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
   * </code>
   */
  java.util.List<io.temporal.fsi.api.applications.v1.RegisterUserResponse>
      getUserRegistrationsList();
  /**
   * <code>
   * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
   * </code>
   */
  io.temporal.fsi.api.applications.v1.RegisterUserResponse getUserRegistrations(int index);
  /**
   * <code>
   * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
   * </code>
   */
  int getUserRegistrationsCount();
  /**
   * <code>
   * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
   * </code>
   */
  java.util.List<? extends io.temporal.fsi.api.applications.v1.RegisterUserResponseOrBuilder>
      getUserRegistrationsOrBuilderList();
  /**
   * <code>
   * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
   * </code>
   */
  io.temporal.fsi.api.applications.v1.RegisterUserResponseOrBuilder getUserRegistrationsOrBuilder(
      int index);
}
