// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: applications/v1/queries.proto
// Protobuf Java Version: 4.31.1

package io.temporal.fsi.api.applications.v1;

/** Protobuf type {@code applications.v1.GetUserRegistrationsResponse} */
@com.google.protobuf.Generated
public final class GetUserRegistrationsResponse extends com.google.protobuf.GeneratedMessage
    implements
    // @@protoc_insertion_point(message_implements:applications.v1.GetUserRegistrationsResponse)
    GetUserRegistrationsResponseOrBuilder {
  private static final long serialVersionUID = 0L;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        GetUserRegistrationsResponse.class.getName());
  }
  // Use GetUserRegistrationsResponse.newBuilder() to construct.
  private GetUserRegistrationsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }

  private GetUserRegistrationsResponse() {
    userRegistrations_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return io.temporal.fsi.api.applications.v1.QueriesProto
        .internal_static_applications_v1_GetUserRegistrationsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.temporal.fsi.api.applications.v1.QueriesProto
        .internal_static_applications_v1_GetUserRegistrationsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse.class,
            io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse.Builder.class);
  }

  public static final int USER_REGISTRATIONS_FIELD_NUMBER = 1;

  @SuppressWarnings("serial")
  private java.util.List<io.temporal.fsi.api.applications.v1.RegisterUserResponse>
      userRegistrations_;
  /**
   * <code>
   * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
   * </code>
   */
  @java.lang.Override
  public java.util.List<io.temporal.fsi.api.applications.v1.RegisterUserResponse>
      getUserRegistrationsList() {
    return userRegistrations_;
  }
  /**
   * <code>
   * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
   * </code>
   */
  @java.lang.Override
  public java.util.List<? extends io.temporal.fsi.api.applications.v1.RegisterUserResponseOrBuilder>
      getUserRegistrationsOrBuilderList() {
    return userRegistrations_;
  }
  /**
   * <code>
   * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
   * </code>
   */
  @java.lang.Override
  public int getUserRegistrationsCount() {
    return userRegistrations_.size();
  }
  /**
   * <code>
   * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
   * </code>
   */
  @java.lang.Override
  public io.temporal.fsi.api.applications.v1.RegisterUserResponse getUserRegistrations(int index) {
    return userRegistrations_.get(index);
  }
  /**
   * <code>
   * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
   * </code>
   */
  @java.lang.Override
  public io.temporal.fsi.api.applications.v1.RegisterUserResponseOrBuilder
      getUserRegistrationsOrBuilder(int index) {
    return userRegistrations_.get(index);
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    for (int i = 0; i < userRegistrations_.size(); i++) {
      output.writeMessage(1, userRegistrations_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < userRegistrations_.size(); i++) {
      size +=
          com.google.protobuf.CodedOutputStream.computeMessageSize(1, userRegistrations_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse)) {
      return super.equals(obj);
    }
    io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse other =
        (io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse) obj;

    if (!getUserRegistrationsList().equals(other.getUserRegistrationsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUserRegistrationsCount() > 0) {
      hash = (37 * hash) + USER_REGISTRATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getUserRegistrationsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse parseFrom(
      java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse parseFrom(
      byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse parseFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
  }

  public static io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
  }

  public static io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
  }

  public static io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(
      io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /** Protobuf type {@code applications.v1.GetUserRegistrationsResponse} */
  public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:applications.v1.GetUserRegistrationsResponse)
      io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return io.temporal.fsi.api.applications.v1.QueriesProto
          .internal_static_applications_v1_GetUserRegistrationsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.temporal.fsi.api.applications.v1.QueriesProto
          .internal_static_applications_v1_GetUserRegistrationsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse.class,
              io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse.Builder.class);
    }

    // Construct using io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse.newBuilder()
    private Builder() {}

    private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (userRegistrationsBuilder_ == null) {
        userRegistrations_ = java.util.Collections.emptyList();
      } else {
        userRegistrations_ = null;
        userRegistrationsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return io.temporal.fsi.api.applications.v1.QueriesProto
          .internal_static_applications_v1_GetUserRegistrationsResponse_descriptor;
    }

    @java.lang.Override
    public io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse
        getDefaultInstanceForType() {
      return io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse build() {
      io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse buildPartial() {
      io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse result =
          new io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(
        io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse result) {
      if (userRegistrationsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          userRegistrations_ = java.util.Collections.unmodifiableList(userRegistrations_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.userRegistrations_ = userRegistrations_;
      } else {
        result.userRegistrations_ = userRegistrationsBuilder_.build();
      }
    }

    private void buildPartial0(
        io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse) {
        return mergeFrom((io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(
        io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse other) {
      if (other
          == io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse.getDefaultInstance())
        return this;
      if (userRegistrationsBuilder_ == null) {
        if (!other.userRegistrations_.isEmpty()) {
          if (userRegistrations_.isEmpty()) {
            userRegistrations_ = other.userRegistrations_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUserRegistrationsIsMutable();
            userRegistrations_.addAll(other.userRegistrations_);
          }
          onChanged();
        }
      } else {
        if (!other.userRegistrations_.isEmpty()) {
          if (userRegistrationsBuilder_.isEmpty()) {
            userRegistrationsBuilder_.dispose();
            userRegistrationsBuilder_ = null;
            userRegistrations_ = other.userRegistrations_;
            bitField0_ = (bitField0_ & ~0x00000001);
            userRegistrationsBuilder_ =
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders
                    ? internalGetUserRegistrationsFieldBuilder()
                    : null;
          } else {
            userRegistrationsBuilder_.addAllMessages(other.userRegistrations_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                io.temporal.fsi.api.applications.v1.RegisterUserResponse m =
                    input.readMessage(
                        io.temporal.fsi.api.applications.v1.RegisterUserResponse.parser(),
                        extensionRegistry);
                if (userRegistrationsBuilder_ == null) {
                  ensureUserRegistrationsIsMutable();
                  userRegistrations_.add(m);
                } else {
                  userRegistrationsBuilder_.addMessage(m);
                }
                break;
              } // case 10
            default:
              {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int bitField0_;

    private java.util.List<io.temporal.fsi.api.applications.v1.RegisterUserResponse>
        userRegistrations_ = java.util.Collections.emptyList();

    private void ensureUserRegistrationsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        userRegistrations_ =
            new java.util.ArrayList<io.temporal.fsi.api.applications.v1.RegisterUserResponse>(
                userRegistrations_);
        bitField0_ |= 0x00000001;
      }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
            io.temporal.fsi.api.applications.v1.RegisterUserResponse,
            io.temporal.fsi.api.applications.v1.RegisterUserResponse.Builder,
            io.temporal.fsi.api.applications.v1.RegisterUserResponseOrBuilder>
        userRegistrationsBuilder_;

    /**
     * <code>
     * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
     * </code>
     */
    public java.util.List<io.temporal.fsi.api.applications.v1.RegisterUserResponse>
        getUserRegistrationsList() {
      if (userRegistrationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(userRegistrations_);
      } else {
        return userRegistrationsBuilder_.getMessageList();
      }
    }
    /**
     * <code>
     * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
     * </code>
     */
    public int getUserRegistrationsCount() {
      if (userRegistrationsBuilder_ == null) {
        return userRegistrations_.size();
      } else {
        return userRegistrationsBuilder_.getCount();
      }
    }
    /**
     * <code>
     * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
     * </code>
     */
    public io.temporal.fsi.api.applications.v1.RegisterUserResponse getUserRegistrations(
        int index) {
      if (userRegistrationsBuilder_ == null) {
        return userRegistrations_.get(index);
      } else {
        return userRegistrationsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>
     * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
     * </code>
     */
    public Builder setUserRegistrations(
        int index, io.temporal.fsi.api.applications.v1.RegisterUserResponse value) {
      if (userRegistrationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserRegistrationsIsMutable();
        userRegistrations_.set(index, value);
        onChanged();
      } else {
        userRegistrationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>
     * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
     * </code>
     */
    public Builder setUserRegistrations(
        int index,
        io.temporal.fsi.api.applications.v1.RegisterUserResponse.Builder builderForValue) {
      if (userRegistrationsBuilder_ == null) {
        ensureUserRegistrationsIsMutable();
        userRegistrations_.set(index, builderForValue.build());
        onChanged();
      } else {
        userRegistrationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>
     * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
     * </code>
     */
    public Builder addUserRegistrations(
        io.temporal.fsi.api.applications.v1.RegisterUserResponse value) {
      if (userRegistrationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserRegistrationsIsMutable();
        userRegistrations_.add(value);
        onChanged();
      } else {
        userRegistrationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>
     * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
     * </code>
     */
    public Builder addUserRegistrations(
        int index, io.temporal.fsi.api.applications.v1.RegisterUserResponse value) {
      if (userRegistrationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserRegistrationsIsMutable();
        userRegistrations_.add(index, value);
        onChanged();
      } else {
        userRegistrationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>
     * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
     * </code>
     */
    public Builder addUserRegistrations(
        io.temporal.fsi.api.applications.v1.RegisterUserResponse.Builder builderForValue) {
      if (userRegistrationsBuilder_ == null) {
        ensureUserRegistrationsIsMutable();
        userRegistrations_.add(builderForValue.build());
        onChanged();
      } else {
        userRegistrationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>
     * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
     * </code>
     */
    public Builder addUserRegistrations(
        int index,
        io.temporal.fsi.api.applications.v1.RegisterUserResponse.Builder builderForValue) {
      if (userRegistrationsBuilder_ == null) {
        ensureUserRegistrationsIsMutable();
        userRegistrations_.add(index, builderForValue.build());
        onChanged();
      } else {
        userRegistrationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>
     * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
     * </code>
     */
    public Builder addAllUserRegistrations(
        java.lang.Iterable<? extends io.temporal.fsi.api.applications.v1.RegisterUserResponse>
            values) {
      if (userRegistrationsBuilder_ == null) {
        ensureUserRegistrationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(values, userRegistrations_);
        onChanged();
      } else {
        userRegistrationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>
     * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
     * </code>
     */
    public Builder clearUserRegistrations() {
      if (userRegistrationsBuilder_ == null) {
        userRegistrations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        userRegistrationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>
     * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
     * </code>
     */
    public Builder removeUserRegistrations(int index) {
      if (userRegistrationsBuilder_ == null) {
        ensureUserRegistrationsIsMutable();
        userRegistrations_.remove(index);
        onChanged();
      } else {
        userRegistrationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>
     * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
     * </code>
     */
    public io.temporal.fsi.api.applications.v1.RegisterUserResponse.Builder
        getUserRegistrationsBuilder(int index) {
      return internalGetUserRegistrationsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>
     * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
     * </code>
     */
    public io.temporal.fsi.api.applications.v1.RegisterUserResponseOrBuilder
        getUserRegistrationsOrBuilder(int index) {
      if (userRegistrationsBuilder_ == null) {
        return userRegistrations_.get(index);
      } else {
        return userRegistrationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>
     * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
     * </code>
     */
    public java.util.List<
            ? extends io.temporal.fsi.api.applications.v1.RegisterUserResponseOrBuilder>
        getUserRegistrationsOrBuilderList() {
      if (userRegistrationsBuilder_ != null) {
        return userRegistrationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(userRegistrations_);
      }
    }
    /**
     * <code>
     * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
     * </code>
     */
    public io.temporal.fsi.api.applications.v1.RegisterUserResponse.Builder
        addUserRegistrationsBuilder() {
      return internalGetUserRegistrationsFieldBuilder()
          .addBuilder(
              io.temporal.fsi.api.applications.v1.RegisterUserResponse.getDefaultInstance());
    }
    /**
     * <code>
     * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
     * </code>
     */
    public io.temporal.fsi.api.applications.v1.RegisterUserResponse.Builder
        addUserRegistrationsBuilder(int index) {
      return internalGetUserRegistrationsFieldBuilder()
          .addBuilder(
              index, io.temporal.fsi.api.applications.v1.RegisterUserResponse.getDefaultInstance());
    }
    /**
     * <code>
     * repeated .applications.v1.RegisterUserResponse user_registrations = 1 [json_name = "userRegistrations"];
     * </code>
     */
    public java.util.List<io.temporal.fsi.api.applications.v1.RegisterUserResponse.Builder>
        getUserRegistrationsBuilderList() {
      return internalGetUserRegistrationsFieldBuilder().getBuilderList();
    }

    private com.google.protobuf.RepeatedFieldBuilder<
            io.temporal.fsi.api.applications.v1.RegisterUserResponse,
            io.temporal.fsi.api.applications.v1.RegisterUserResponse.Builder,
            io.temporal.fsi.api.applications.v1.RegisterUserResponseOrBuilder>
        internalGetUserRegistrationsFieldBuilder() {
      if (userRegistrationsBuilder_ == null) {
        userRegistrationsBuilder_ =
            new com.google.protobuf.RepeatedFieldBuilder<
                io.temporal.fsi.api.applications.v1.RegisterUserResponse,
                io.temporal.fsi.api.applications.v1.RegisterUserResponse.Builder,
                io.temporal.fsi.api.applications.v1.RegisterUserResponseOrBuilder>(
                userRegistrations_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        userRegistrations_ = null;
      }
      return userRegistrationsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:applications.v1.GetUserRegistrationsResponse)
  }

  // @@protoc_insertion_point(class_scope:applications.v1.GetUserRegistrationsResponse)
  private static final io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse
      DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse();
  }

  public static io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse
      getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetUserRegistrationsResponse> PARSER =
      new com.google.protobuf.AbstractParser<GetUserRegistrationsResponse>() {
        @java.lang.Override
        public GetUserRegistrationsResponse parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

  public static com.google.protobuf.Parser<GetUserRegistrationsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetUserRegistrationsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.temporal.fsi.api.applications.v1.GetUserRegistrationsResponse
      getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
