// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: applications/v1/commands.proto
// Protobuf Java Version: 4.31.1

package io.temporal.fsi.api.applications.v1;

@com.google.protobuf.Generated
public interface MatchClientRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:applications.v1.MatchClientRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ssn = 1 [json_name = "ssn"];</code>
   *
   * @return The ssn.
   */
  java.lang.String getSsn();
  /**
   * <code>string ssn = 1 [json_name = "ssn"];</code>
   *
   * @return The bytes for ssn.
   */
  com.google.protobuf.ByteString getSsnBytes();

  /**
   * <code>string birthdate = 2 [json_name = "birthdate"];</code>
   *
   * @return The birthdate.
   */
  java.lang.String getBirthdate();
  /**
   * <code>string birthdate = 2 [json_name = "birthdate"];</code>
   *
   * @return The bytes for birthdate.
   */
  com.google.protobuf.ByteString getBirthdateBytes();

  /**
   * <code>string name = 3 [json_name = "name"];</code>
   *
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3 [json_name = "name"];</code>
   *
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString getNameBytes();
}
