// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: applications/v1/commands.proto
// Protobuf Java Version: 4.31.1

package io.temporal.fsi.api.applications.v1;

/** Protobuf type {@code applications.v1.MatchClientResponse} */
@com.google.protobuf.Generated
public final class MatchClientResponse extends com.google.protobuf.GeneratedMessage
    implements
    // @@protoc_insertion_point(message_implements:applications.v1.MatchClientResponse)
    MatchClientResponseOrBuilder {
  private static final long serialVersionUID = 0L;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        MatchClientResponse.class.getName());
  }
  // Use MatchClientResponse.newBuilder() to construct.
  private MatchClientResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }

  private MatchClientResponse() {
    clientId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return io.temporal.fsi.api.applications.v1.CommandsProto
        .internal_static_applications_v1_MatchClientResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.temporal.fsi.api.applications.v1.CommandsProto
        .internal_static_applications_v1_MatchClientResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.temporal.fsi.api.applications.v1.MatchClientResponse.class,
            io.temporal.fsi.api.applications.v1.MatchClientResponse.Builder.class);
  }

  public static final int CLIENT_ID_FIELD_NUMBER = 1;

  @SuppressWarnings("serial")
  private volatile java.lang.Object clientId_ = "";
  /**
   * <code>string client_id = 1 [json_name = "clientId"];</code>
   *
   * @return The clientId.
   */
  @java.lang.Override
  public java.lang.String getClientId() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientId_ = s;
      return s;
    }
  }
  /**
   * <code>string client_id = 1 [json_name = "clientId"];</code>
   *
   * @return The bytes for clientId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getClientIdBytes() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      clientId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOT_FOUND_FIELD_NUMBER = 2;
  private boolean notFound_ = false;
  /**
   * <code>bool not_found = 2 [json_name = "notFound"];</code>
   *
   * @return The notFound.
   */
  @java.lang.Override
  public boolean getNotFound() {
    return notFound_;
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(clientId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, clientId_);
    }
    if (notFound_ != false) {
      output.writeBool(2, notFound_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(clientId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, clientId_);
    }
    if (notFound_ != false) {
      size += com.google.protobuf.CodedOutputStream.computeBoolSize(2, notFound_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof io.temporal.fsi.api.applications.v1.MatchClientResponse)) {
      return super.equals(obj);
    }
    io.temporal.fsi.api.applications.v1.MatchClientResponse other =
        (io.temporal.fsi.api.applications.v1.MatchClientResponse) obj;

    if (!getClientId().equals(other.getClientId())) return false;
    if (getNotFound() != other.getNotFound()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLIENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getClientId().hashCode();
    hash = (37 * hash) + NOT_FOUND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(getNotFound());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.temporal.fsi.api.applications.v1.MatchClientResponse parseFrom(
      java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.temporal.fsi.api.applications.v1.MatchClientResponse parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.temporal.fsi.api.applications.v1.MatchClientResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.temporal.fsi.api.applications.v1.MatchClientResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.temporal.fsi.api.applications.v1.MatchClientResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.temporal.fsi.api.applications.v1.MatchClientResponse parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.temporal.fsi.api.applications.v1.MatchClientResponse parseFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
  }

  public static io.temporal.fsi.api.applications.v1.MatchClientResponse parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static io.temporal.fsi.api.applications.v1.MatchClientResponse parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
  }

  public static io.temporal.fsi.api.applications.v1.MatchClientResponse parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static io.temporal.fsi.api.applications.v1.MatchClientResponse parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
  }

  public static io.temporal.fsi.api.applications.v1.MatchClientResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(
      io.temporal.fsi.api.applications.v1.MatchClientResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /** Protobuf type {@code applications.v1.MatchClientResponse} */
  public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:applications.v1.MatchClientResponse)
      io.temporal.fsi.api.applications.v1.MatchClientResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return io.temporal.fsi.api.applications.v1.CommandsProto
          .internal_static_applications_v1_MatchClientResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.temporal.fsi.api.applications.v1.CommandsProto
          .internal_static_applications_v1_MatchClientResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.temporal.fsi.api.applications.v1.MatchClientResponse.class,
              io.temporal.fsi.api.applications.v1.MatchClientResponse.Builder.class);
    }

    // Construct using io.temporal.fsi.api.applications.v1.MatchClientResponse.newBuilder()
    private Builder() {}

    private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      clientId_ = "";
      notFound_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return io.temporal.fsi.api.applications.v1.CommandsProto
          .internal_static_applications_v1_MatchClientResponse_descriptor;
    }

    @java.lang.Override
    public io.temporal.fsi.api.applications.v1.MatchClientResponse getDefaultInstanceForType() {
      return io.temporal.fsi.api.applications.v1.MatchClientResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.temporal.fsi.api.applications.v1.MatchClientResponse build() {
      io.temporal.fsi.api.applications.v1.MatchClientResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.temporal.fsi.api.applications.v1.MatchClientResponse buildPartial() {
      io.temporal.fsi.api.applications.v1.MatchClientResponse result =
          new io.temporal.fsi.api.applications.v1.MatchClientResponse(this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.temporal.fsi.api.applications.v1.MatchClientResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.clientId_ = clientId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.notFound_ = notFound_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.temporal.fsi.api.applications.v1.MatchClientResponse) {
        return mergeFrom((io.temporal.fsi.api.applications.v1.MatchClientResponse) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.temporal.fsi.api.applications.v1.MatchClientResponse other) {
      if (other == io.temporal.fsi.api.applications.v1.MatchClientResponse.getDefaultInstance())
        return this;
      if (!other.getClientId().isEmpty()) {
        clientId_ = other.clientId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getNotFound() != false) {
        setNotFound(other.getNotFound());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                clientId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
            case 16:
              {
                notFound_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
            default:
              {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int bitField0_;

    private java.lang.Object clientId_ = "";
    /**
     * <code>string client_id = 1 [json_name = "clientId"];</code>
     *
     * @return The clientId.
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string client_id = 1 [json_name = "clientId"];</code>
     *
     * @return The bytes for clientId.
     */
    public com.google.protobuf.ByteString getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string client_id = 1 [json_name = "clientId"];</code>
     *
     * @param value The clientId to set.
     * @return This builder for chaining.
     */
    public Builder setClientId(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      clientId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string client_id = 1 [json_name = "clientId"];</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearClientId() {
      clientId_ = getDefaultInstance().getClientId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string client_id = 1 [json_name = "clientId"];</code>
     *
     * @param value The bytes for clientId to set.
     * @return This builder for chaining.
     */
    public Builder setClientIdBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      clientId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean notFound_;
    /**
     * <code>bool not_found = 2 [json_name = "notFound"];</code>
     *
     * @return The notFound.
     */
    @java.lang.Override
    public boolean getNotFound() {
      return notFound_;
    }
    /**
     * <code>bool not_found = 2 [json_name = "notFound"];</code>
     *
     * @param value The notFound to set.
     * @return This builder for chaining.
     */
    public Builder setNotFound(boolean value) {

      notFound_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool not_found = 2 [json_name = "notFound"];</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearNotFound() {
      bitField0_ = (bitField0_ & ~0x00000002);
      notFound_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:applications.v1.MatchClientResponse)
  }

  // @@protoc_insertion_point(class_scope:applications.v1.MatchClientResponse)
  private static final io.temporal.fsi.api.applications.v1.MatchClientResponse DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new io.temporal.fsi.api.applications.v1.MatchClientResponse();
  }

  public static io.temporal.fsi.api.applications.v1.MatchClientResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MatchClientResponse> PARSER =
      new com.google.protobuf.AbstractParser<MatchClientResponse>() {
        @java.lang.Override
        public MatchClientResponse parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

  public static com.google.protobuf.Parser<MatchClientResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MatchClientResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.temporal.fsi.api.applications.v1.MatchClientResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
