// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: applications/v1/queries.proto
// Protobuf Java Version: 4.31.1

package io.temporal.fsi.api.applications.v1;

@com.google.protobuf.Generated
public final class QueriesProto {
  private QueriesProto() {}

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        QueriesProto.class.getName());
  }

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_applications_v1_GetUserRegistrationsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_applications_v1_GetUserRegistrationsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\035applications/v1/queries.proto\022\017applica"
          + "tions.v1\032\034applications/v1/values.proto\032\036"
          + "applications/v1/commands.proto\"\241\001\n\034GetUs"
          + "erRegistrationsResponse\022T\n\022user_registra"
          + "tions\030\001 \003(\0132%.applications.v1.RegisterUs"
          + "erResponseR\021userRegistrations\022+\n\005users\030\002"
          + " \003(\0132\025.applications.v1.UserR\005usersB\220\001\n#i"
          + "o.temporal.fsi.api.applications.v1B\014Quer"
          + "iesProtoP\001\242\002\003AXX\252\002\017Applications.V1\312\002\017App"
          + "lications\\V1\342\002\033Applications\\V1\\GPBMetada"
          + "ta\352\002\020Applications::V1b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              io.temporal.fsi.api.applications.v1.ValuesProto.getDescriptor(),
              io.temporal.fsi.api.applications.v1.CommandsProto.getDescriptor(),
            });
    internal_static_applications_v1_GetUserRegistrationsResponse_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_applications_v1_GetUserRegistrationsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_applications_v1_GetUserRegistrationsResponse_descriptor,
            new java.lang.String[] {
              "UserRegistrations", "Users",
            });
    descriptor.resolveAllFeaturesImmutable();
    io.temporal.fsi.api.applications.v1.ValuesProto.getDescriptor();
    io.temporal.fsi.api.applications.v1.CommandsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
