// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: applications/v1/queries.proto
// Protobuf Java Version: 4.31.1

package io.temporal.fsi.api.applications.v1;

@com.google.protobuf.Generated
public final class QueriesProto {
  private QueriesProto() {}

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        QueriesProto.class.getName());
  }

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_applications_v1_GetUserRegistrationsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_applications_v1_GetUserRegistrationsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_applications_v1_GetWealthManagementAccountResponse_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_applications_v1_GetWealthManagementAccountResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\035applications/v1/queries.proto\022\017applica"
          + "tions.v1\032\034applications/v1/values.proto\032\036"
          + "applications/v1/commands.proto\032\037applicat"
          + "ions/v1/workflows.proto\"\241\001\n\034GetUserRegis"
          + "trationsResponse\022T\n\022user_registrations\030\001"
          + " \003(\0132%.applications.v1.RegisterUserRespo"
          + "nseR\021userRegistrations\022+\n\005users\030\002 \003(\0132\025."
          + "applications.v1.UserR\005users\"\323\002\n\"GetWealt"
          + "hManagementAccountResponse\022G\n\004args\030\001 \001(\013"
          + "23.applications.v1.OpenWealthManagementA"
          + "ccountRequestR\004args\022\027\n\007user_id\030\002 \001(\tR\006us"
          + "erId\022\022\n\004name\030\003 \001(\tR\004name\022\033\n\tclient_id\030\004 "
          + "\001(\tR\010clientId\022!\n\014is_completed\030\005 \001(\010R\013isC"
          + "ompleted\022\020\n\003ssn\030\006 \001(\tR\003ssn\022\034\n\tbirthdate\030"
          + "\007 \001(\tR\tbirthdate\022G\n\014match_client\030\010 \001(\0132$"
          + ".applications.v1.MatchClientResponseR\013ma"
          + "tchClientB\220\001\n#io.temporal.fsi.api.applic"
          + "ations.v1B\014QueriesProtoP\001\242\002\003AXX\252\002\017Applic"
          + "ations.V1\312\002\017Applications\\V1\342\002\033Applicatio"
          + "ns\\V1\\GPBMetadata\352\002\020Applications::V1b\006pr"
          + "oto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              io.temporal.fsi.api.applications.v1.ValuesProto.getDescriptor(),
              io.temporal.fsi.api.applications.v1.CommandsProto.getDescriptor(),
              io.temporal.fsi.api.applications.v1.WorkflowsProto.getDescriptor(),
            });
    internal_static_applications_v1_GetUserRegistrationsResponse_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_applications_v1_GetUserRegistrationsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_applications_v1_GetUserRegistrationsResponse_descriptor,
            new java.lang.String[] {
              "UserRegistrations", "Users",
            });
    internal_static_applications_v1_GetWealthManagementAccountResponse_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_applications_v1_GetWealthManagementAccountResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_applications_v1_GetWealthManagementAccountResponse_descriptor,
            new java.lang.String[] {
              "Args",
              "UserId",
              "Name",
              "ClientId",
              "IsCompleted",
              "Ssn",
              "Birthdate",
              "MatchClient",
            });
    descriptor.resolveAllFeaturesImmutable();
    io.temporal.fsi.api.applications.v1.ValuesProto.getDescriptor();
    io.temporal.fsi.api.applications.v1.CommandsProto.getDescriptor();
    io.temporal.fsi.api.applications.v1.WorkflowsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
