// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: applications/v1/workflows.proto
// Protobuf Java Version: 4.31.1

package io.temporal.fsi.api.applications.v1;

@com.google.protobuf.Generated
public interface StartApplicationRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:applications.v1.StartApplicationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   *
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1 [json_name = "userId"];</code>
   *
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString getUserIdBytes();

  /**
   * <code>string ssn = 2 [json_name = "ssn"];</code>
   *
   * @return The ssn.
   */
  java.lang.String getSsn();
  /**
   * <code>string ssn = 2 [json_name = "ssn"];</code>
   *
   * @return The bytes for ssn.
   */
  com.google.protobuf.ByteString getSsnBytes();

  /**
   * <code>string birthdate = 3 [json_name = "birthdate"];</code>
   *
   * @return The birthdate.
   */
  java.lang.String getBirthdate();
  /**
   * <code>string birthdate = 3 [json_name = "birthdate"];</code>
   *
   * @return The bytes for birthdate.
   */
  com.google.protobuf.ByteString getBirthdateBytes();
}
