// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: applications/v1/workflows.proto
// Protobuf Java Version: 4.31.1

package io.temporal.fsi.api.applications.v1;

@com.google.protobuf.Generated
public final class WorkflowsProto {
  private WorkflowsProto() {}

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        WorkflowsProto.class.getName());
  }

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_applications_v1_StartUserRegistrationsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_applications_v1_StartUserRegistrationsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_applications_v1_OpenWealthManagementAccountRequest_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_applications_v1_OpenWealthManagementAccountRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\037applications/v1/workflows.proto\022\017appli"
          + "cations.v1\"3\n\035StartUserRegistrationsRequ"
          + "est\022\022\n\004name\030\001 \001(\tR\004name\"=\n\"OpenWealthMan"
          + "agementAccountRequest\022\027\n\007user_id\030\001 \001(\tR\006"
          + "userIdB\222\001\n#io.temporal.fsi.api.applicati"
          + "ons.v1B\016WorkflowsProtoP\001\242\002\003AXX\252\002\017Applica"
          + "tions.V1\312\002\017Applications\\V1\342\002\033Application"
          + "s\\V1\\GPBMetadata\352\002\020Applications::V1b\006pro"
          + "to3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {});
    internal_static_applications_v1_StartUserRegistrationsRequest_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_applications_v1_StartUserRegistrationsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_applications_v1_StartUserRegistrationsRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_applications_v1_OpenWealthManagementAccountRequest_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_applications_v1_OpenWealthManagementAccountRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_applications_v1_OpenWealthManagementAccountRequest_descriptor,
            new java.lang.String[] {
              "UserId",
            });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
