// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: web/v1/message.proto
// Protobuf Java Version: 4.31.1

package io.temporal.fsi.api.web.v1;

/** Protobuf type {@code web.v1.AccountsPut} */
@com.google.protobuf.Generated
public final class AccountsPut extends com.google.protobuf.GeneratedMessage
    implements
    // @@protoc_insertion_point(message_implements:web.v1.AccountsPut)
    AccountsPutOrBuilder {
  private static final long serialVersionUID = 0L;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        AccountsPut.class.getName());
  }
  // Use AccountsPut.newBuilder() to construct.
  private AccountsPut(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }

  private AccountsPut() {
    ssn_ = "";
    birthdate_ = "";
    name_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return io.temporal.fsi.api.web.v1.MessageProto.internal_static_web_v1_AccountsPut_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.temporal.fsi.api.web.v1.MessageProto
        .internal_static_web_v1_AccountsPut_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.temporal.fsi.api.web.v1.AccountsPut.class,
            io.temporal.fsi.api.web.v1.AccountsPut.Builder.class);
  }

  private int bitField0_;
  public static final int SSN_FIELD_NUMBER = 1;

  @SuppressWarnings("serial")
  private volatile java.lang.Object ssn_ = "";
  /**
   * <code>optional string ssn = 1 [json_name = "ssn"];</code>
   *
   * @return Whether the ssn field is set.
   */
  @java.lang.Override
  public boolean hasSsn() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string ssn = 1 [json_name = "ssn"];</code>
   *
   * @return The ssn.
   */
  @java.lang.Override
  public java.lang.String getSsn() {
    java.lang.Object ref = ssn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ssn_ = s;
      return s;
    }
  }
  /**
   * <code>optional string ssn = 1 [json_name = "ssn"];</code>
   *
   * @return The bytes for ssn.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSsnBytes() {
    java.lang.Object ref = ssn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      ssn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BIRTHDATE_FIELD_NUMBER = 2;

  @SuppressWarnings("serial")
  private volatile java.lang.Object birthdate_ = "";
  /**
   * <code>optional string birthdate = 2 [json_name = "birthdate"];</code>
   *
   * @return Whether the birthdate field is set.
   */
  @java.lang.Override
  public boolean hasBirthdate() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string birthdate = 2 [json_name = "birthdate"];</code>
   *
   * @return The birthdate.
   */
  @java.lang.Override
  public java.lang.String getBirthdate() {
    java.lang.Object ref = birthdate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      birthdate_ = s;
      return s;
    }
  }
  /**
   * <code>optional string birthdate = 2 [json_name = "birthdate"];</code>
   *
   * @return The bytes for birthdate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBirthdateBytes() {
    java.lang.Object ref = birthdate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      birthdate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 3;

  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>optional string name = 3 [json_name = "name"];</code>
   *
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string name = 3 [json_name = "name"];</code>
   *
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string name = 3 [json_name = "name"];</code>
   *
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, ssn_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, birthdate_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, name_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, ssn_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, birthdate_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, name_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof io.temporal.fsi.api.web.v1.AccountsPut)) {
      return super.equals(obj);
    }
    io.temporal.fsi.api.web.v1.AccountsPut other = (io.temporal.fsi.api.web.v1.AccountsPut) obj;

    if (hasSsn() != other.hasSsn()) return false;
    if (hasSsn()) {
      if (!getSsn().equals(other.getSsn())) return false;
    }
    if (hasBirthdate() != other.hasBirthdate()) return false;
    if (hasBirthdate()) {
      if (!getBirthdate().equals(other.getBirthdate())) return false;
    }
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName().equals(other.getName())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSsn()) {
      hash = (37 * hash) + SSN_FIELD_NUMBER;
      hash = (53 * hash) + getSsn().hashCode();
    }
    if (hasBirthdate()) {
      hash = (37 * hash) + BIRTHDATE_FIELD_NUMBER;
      hash = (53 * hash) + getBirthdate().hashCode();
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.temporal.fsi.api.web.v1.AccountsPut parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.temporal.fsi.api.web.v1.AccountsPut parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.temporal.fsi.api.web.v1.AccountsPut parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.temporal.fsi.api.web.v1.AccountsPut parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.temporal.fsi.api.web.v1.AccountsPut parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.temporal.fsi.api.web.v1.AccountsPut parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.temporal.fsi.api.web.v1.AccountsPut parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
  }

  public static io.temporal.fsi.api.web.v1.AccountsPut parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static io.temporal.fsi.api.web.v1.AccountsPut parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
  }

  public static io.temporal.fsi.api.web.v1.AccountsPut parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static io.temporal.fsi.api.web.v1.AccountsPut parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
  }

  public static io.temporal.fsi.api.web.v1.AccountsPut parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(io.temporal.fsi.api.web.v1.AccountsPut prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /** Protobuf type {@code web.v1.AccountsPut} */
  public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:web.v1.AccountsPut)
      io.temporal.fsi.api.web.v1.AccountsPutOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return io.temporal.fsi.api.web.v1.MessageProto.internal_static_web_v1_AccountsPut_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.temporal.fsi.api.web.v1.MessageProto
          .internal_static_web_v1_AccountsPut_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.temporal.fsi.api.web.v1.AccountsPut.class,
              io.temporal.fsi.api.web.v1.AccountsPut.Builder.class);
    }

    // Construct using io.temporal.fsi.api.web.v1.AccountsPut.newBuilder()
    private Builder() {}

    private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      ssn_ = "";
      birthdate_ = "";
      name_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return io.temporal.fsi.api.web.v1.MessageProto.internal_static_web_v1_AccountsPut_descriptor;
    }

    @java.lang.Override
    public io.temporal.fsi.api.web.v1.AccountsPut getDefaultInstanceForType() {
      return io.temporal.fsi.api.web.v1.AccountsPut.getDefaultInstance();
    }

    @java.lang.Override
    public io.temporal.fsi.api.web.v1.AccountsPut build() {
      io.temporal.fsi.api.web.v1.AccountsPut result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.temporal.fsi.api.web.v1.AccountsPut buildPartial() {
      io.temporal.fsi.api.web.v1.AccountsPut result =
          new io.temporal.fsi.api.web.v1.AccountsPut(this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.temporal.fsi.api.web.v1.AccountsPut result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.ssn_ = ssn_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.birthdate_ = birthdate_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.name_ = name_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.temporal.fsi.api.web.v1.AccountsPut) {
        return mergeFrom((io.temporal.fsi.api.web.v1.AccountsPut) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.temporal.fsi.api.web.v1.AccountsPut other) {
      if (other == io.temporal.fsi.api.web.v1.AccountsPut.getDefaultInstance()) return this;
      if (other.hasSsn()) {
        ssn_ = other.ssn_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasBirthdate()) {
        birthdate_ = other.birthdate_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasName()) {
        name_ = other.name_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                ssn_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
            case 18:
              {
                birthdate_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
            case 26:
              {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
            default:
              {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int bitField0_;

    private java.lang.Object ssn_ = "";
    /**
     * <code>optional string ssn = 1 [json_name = "ssn"];</code>
     *
     * @return Whether the ssn field is set.
     */
    public boolean hasSsn() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string ssn = 1 [json_name = "ssn"];</code>
     *
     * @return The ssn.
     */
    public java.lang.String getSsn() {
      java.lang.Object ref = ssn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ssn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string ssn = 1 [json_name = "ssn"];</code>
     *
     * @return The bytes for ssn.
     */
    public com.google.protobuf.ByteString getSsnBytes() {
      java.lang.Object ref = ssn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        ssn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string ssn = 1 [json_name = "ssn"];</code>
     *
     * @param value The ssn to set.
     * @return This builder for chaining.
     */
    public Builder setSsn(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ssn_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional string ssn = 1 [json_name = "ssn"];</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearSsn() {
      ssn_ = getDefaultInstance().getSsn();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>optional string ssn = 1 [json_name = "ssn"];</code>
     *
     * @param value The bytes for ssn to set.
     * @return This builder for chaining.
     */
    public Builder setSsnBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      ssn_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object birthdate_ = "";
    /**
     * <code>optional string birthdate = 2 [json_name = "birthdate"];</code>
     *
     * @return Whether the birthdate field is set.
     */
    public boolean hasBirthdate() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string birthdate = 2 [json_name = "birthdate"];</code>
     *
     * @return The birthdate.
     */
    public java.lang.String getBirthdate() {
      java.lang.Object ref = birthdate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        birthdate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string birthdate = 2 [json_name = "birthdate"];</code>
     *
     * @return The bytes for birthdate.
     */
    public com.google.protobuf.ByteString getBirthdateBytes() {
      java.lang.Object ref = birthdate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        birthdate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string birthdate = 2 [json_name = "birthdate"];</code>
     *
     * @param value The birthdate to set.
     * @return This builder for chaining.
     */
    public Builder setBirthdate(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      birthdate_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string birthdate = 2 [json_name = "birthdate"];</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearBirthdate() {
      birthdate_ = getDefaultInstance().getBirthdate();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string birthdate = 2 [json_name = "birthdate"];</code>
     *
     * @param value The bytes for birthdate to set.
     * @return This builder for chaining.
     */
    public Builder setBirthdateBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      birthdate_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 3 [json_name = "name"];</code>
     *
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string name = 3 [json_name = "name"];</code>
     *
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 3 [json_name = "name"];</code>
     *
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 3 [json_name = "name"];</code>
     *
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      name_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 3 [json_name = "name"];</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 3 [json_name = "name"];</code>
     *
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:web.v1.AccountsPut)
  }

  // @@protoc_insertion_point(class_scope:web.v1.AccountsPut)
  private static final io.temporal.fsi.api.web.v1.AccountsPut DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new io.temporal.fsi.api.web.v1.AccountsPut();
  }

  public static io.temporal.fsi.api.web.v1.AccountsPut getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AccountsPut> PARSER =
      new com.google.protobuf.AbstractParser<AccountsPut>() {
        @java.lang.Override
        public AccountsPut parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

  public static com.google.protobuf.Parser<AccountsPut> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AccountsPut> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.temporal.fsi.api.web.v1.AccountsPut getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
