// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: web/v1/message.proto
// Protobuf Java Version: 4.31.1

package io.temporal.fsi.api.web.v1;

@com.google.protobuf.Generated
public interface ApplicationsPutOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:web.v1.ApplicationsPut)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string ssn = 1 [json_name = "ssn"];</code>
   *
   * @return Whether the ssn field is set.
   */
  boolean hasSsn();
  /**
   * <code>optional string ssn = 1 [json_name = "ssn"];</code>
   *
   * @return The ssn.
   */
  java.lang.String getSsn();
  /**
   * <code>optional string ssn = 1 [json_name = "ssn"];</code>
   *
   * @return The bytes for ssn.
   */
  com.google.protobuf.ByteString getSsnBytes();

  /**
   * <code>optional string birthdate = 2 [json_name = "birthdate"];</code>
   *
   * @return Whether the birthdate field is set.
   */
  boolean hasBirthdate();
  /**
   * <code>optional string birthdate = 2 [json_name = "birthdate"];</code>
   *
   * @return The birthdate.
   */
  java.lang.String getBirthdate();
  /**
   * <code>optional string birthdate = 2 [json_name = "birthdate"];</code>
   *
   * @return The bytes for birthdate.
   */
  com.google.protobuf.ByteString getBirthdateBytes();

  /**
   * <code>optional string name = 3 [json_name = "name"];</code>
   *
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 3 [json_name = "name"];</code>
   *
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 3 [json_name = "name"];</code>
   *
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString getNameBytes();
}
