// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: web/v1/message.proto
// Protobuf Java Version: 4.31.1

package io.temporal.fsi.api.web.v1;

@com.google.protobuf.Generated
public interface RegistrationsPutOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:web.v1.RegistrationsPut)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1 [json_name = "email"];</code>
   *
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1 [json_name = "email"];</code>
   *
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString getEmailBytes();
}
