// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: jumpstart/domain/inframanager/v1/values.proto
// Protobuf Java Version: 4.28.3

package io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1;

/** Protobuf enum {@code jumpstart.domain.inframanager.values.v1.ApprovalStatus} */
public enum ApprovalStatus implements com.google.protobuf.ProtocolMessageEnum {
  /** <code>APPROVAL_STATUS_UNSPECIFIED = 0;</code> */
  APPROVAL_STATUS_UNSPECIFIED(0),
  /** <code>APPROVAL_STATUS_PENDING = 1;</code> */
  APPROVAL_STATUS_PENDING(1),
  /** <code>APPROVAL_STATUS_REJECTED = 2;</code> */
  APPROVAL_STATUS_REJECTED(2),
  /** <code>APPROVAL_STATUS_APPROVED = 3;</code> */
  APPROVAL_STATUS_APPROVED(3),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        ApprovalStatus.class.getName());
  }
  /** <code>APPROVAL_STATUS_UNSPECIFIED = 0;</code> */
  public static final int APPROVAL_STATUS_UNSPECIFIED_VALUE = 0;
  /** <code>APPROVAL_STATUS_PENDING = 1;</code> */
  public static final int APPROVAL_STATUS_PENDING_VALUE = 1;
  /** <code>APPROVAL_STATUS_REJECTED = 2;</code> */
  public static final int APPROVAL_STATUS_REJECTED_VALUE = 2;
  /** <code>APPROVAL_STATUS_APPROVED = 3;</code> */
  public static final int APPROVAL_STATUS_APPROVED_VALUE = 3;

  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ApprovalStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ApprovalStatus forNumber(int value) {
    switch (value) {
      case 0:
        return APPROVAL_STATUS_UNSPECIFIED;
      case 1:
        return APPROVAL_STATUS_PENDING;
      case 2:
        return APPROVAL_STATUS_REJECTED;
      case 3:
        return APPROVAL_STATUS_APPROVED;
      default:
        return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ApprovalStatus> internalGetValueMap() {
    return internalValueMap;
  }

  private static final com.google.protobuf.Internal.EnumLiteMap<ApprovalStatus> internalValueMap =
      new com.google.protobuf.Internal.EnumLiteMap<ApprovalStatus>() {
        public ApprovalStatus findValueByNumber(int number) {
          return ApprovalStatus.forNumber(number);
        }
      };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }

  public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
    return getDescriptor();
  }

  public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
    return io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.ValuesProto
        .getDescriptor()
        .getEnumTypes()
        .get(0);
  }

  private static final ApprovalStatus[] VALUES = values();

  public static ApprovalStatus valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException("EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ApprovalStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:jumpstart.domain.inframanager.values.v1.ApprovalStatus)
}
