// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: jumpstart/domain/inframanager/v1/values.proto
// Protobuf Java Version: 4.28.3

package io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1;

/** Protobuf type {@code jumpstart.domain.inframanager.values.v1.Approval} */
public final class Approval extends com.google.protobuf.GeneratedMessage
    implements
    // @@protoc_insertion_point(message_implements:jumpstart.domain.inframanager.values.v1.Approval)
    ApprovalOrBuilder {
  private static final long serialVersionUID = 0L;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        Approval.class.getName());
  }
  // Use Approval.newBuilder() to construct.
  private Approval(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }

  private Approval() {
    status_ = 0;
    comment_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.ValuesProto
        .internal_static_jumpstart_domain_inframanager_values_v1_Approval_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.ValuesProto
        .internal_static_jumpstart_domain_inframanager_values_v1_Approval_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval
                .class,
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval
                .Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_ = 0;
  /**
   * <code>
   * .jumpstart.domain.inframanager.values.v1.ApprovalStatus status = 1 [json_name = "status"];
   * </code>
   *
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>
   * .jumpstart.domain.inframanager.values.v1.ApprovalStatus status = 1 [json_name = "status"];
   * </code>
   *
   * @return The status.
   */
  @java.lang.Override
  public io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.ApprovalStatus
      getStatus() {
    io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.ApprovalStatus
        result =
            io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.ApprovalStatus
                .forNumber(status_);
    return result == null
        ? io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.ApprovalStatus
            .UNRECOGNIZED
        : result;
  }

  public static final int COMMENT_FIELD_NUMBER = 2;

  @SuppressWarnings("serial")
  private volatile java.lang.Object comment_ = "";
  /**
   * <code>string comment = 2 [json_name = "comment"];</code>
   *
   * @return The comment.
   */
  @java.lang.Override
  public java.lang.String getComment() {
    java.lang.Object ref = comment_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      comment_ = s;
      return s;
    }
  }
  /**
   * <code>string comment = 2 [json_name = "comment"];</code>
   *
   * @return The bytes for comment.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getCommentBytes() {
    java.lang.Object ref = comment_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      comment_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (status_
        != io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.ApprovalStatus
            .APPROVAL_STATUS_UNSPECIFIED
            .getNumber()) {
      output.writeEnum(1, status_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(comment_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, comment_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_
        != io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.ApprovalStatus
            .APPROVAL_STATUS_UNSPECIFIED
            .getNumber()) {
      size += com.google.protobuf.CodedOutputStream.computeEnumSize(1, status_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(comment_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, comment_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj
        instanceof
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval)) {
      return super.equals(obj);
    }
    io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval other =
        (io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval) obj;

    if (status_ != other.status_) return false;
    if (!getComment().equals(other.getComment())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + COMMENT_FIELD_NUMBER;
    hash = (53 * hash) + getComment().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval
      parseFrom(java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval
      parseFrom(
          java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval
      parseFrom(com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval
      parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval
      parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval
      parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval
      parseFrom(java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval
      parseFrom(
          java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval
      parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval
      parseDelimitedFrom(
          java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval
      parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval
      parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(
      io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval
          prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /** Protobuf type {@code jumpstart.domain.inframanager.values.v1.Approval} */
  public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:jumpstart.domain.inframanager.values.v1.Approval)
      io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.ApprovalOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.ValuesProto
          .internal_static_jumpstart_domain_inframanager_values_v1_Approval_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.ValuesProto
          .internal_static_jumpstart_domain_inframanager_values_v1_Approval_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval
                  .class,
              io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval
                  .Builder.class);
    }

    // Construct using
    // io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval.newBuilder()
    private Builder() {}

    private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      status_ = 0;
      comment_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.ValuesProto
          .internal_static_jumpstart_domain_inframanager_values_v1_Approval_descriptor;
    }

    @java.lang.Override
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval
        getDefaultInstanceForType() {
      return io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval
          .getDefaultInstance();
    }

    @java.lang.Override
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval
        build() {
      io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval result =
          buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval
        buildPartial() {
      io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval result =
          new io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval(
              this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartial0(
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.comment_ = comment_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other
          instanceof
          io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval) {
        return mergeFrom(
            (io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval)
                other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval other) {
      if (other
          == io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval
              .getDefaultInstance()) return this;
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (!other.getComment().isEmpty()) {
        comment_ = other.comment_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8:
              {
                status_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
            case 18:
              {
                comment_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
            default:
              {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int bitField0_;

    private int status_ = 0;
    /**
     * <code>
     * .jumpstart.domain.inframanager.values.v1.ApprovalStatus status = 1 [json_name = "status"];
     * </code>
     *
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.values.v1.ApprovalStatus status = 1 [json_name = "status"];
     * </code>
     *
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.values.v1.ApprovalStatus status = 1 [json_name = "status"];
     * </code>
     *
     * @return The status.
     */
    @java.lang.Override
    public io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.ApprovalStatus
        getStatus() {
      io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.ApprovalStatus
          result =
              io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1
                  .ApprovalStatus.forNumber(status_);
      return result == null
          ? io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.ApprovalStatus
              .UNRECOGNIZED
          : result;
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.values.v1.ApprovalStatus status = 1 [json_name = "status"];
     * </code>
     *
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.ApprovalStatus
            value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>
     * .jumpstart.domain.inframanager.values.v1.ApprovalStatus status = 1 [json_name = "status"];
     * </code>
     *
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object comment_ = "";
    /**
     * <code>string comment = 2 [json_name = "comment"];</code>
     *
     * @return The comment.
     */
    public java.lang.String getComment() {
      java.lang.Object ref = comment_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        comment_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string comment = 2 [json_name = "comment"];</code>
     *
     * @return The bytes for comment.
     */
    public com.google.protobuf.ByteString getCommentBytes() {
      java.lang.Object ref = comment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        comment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string comment = 2 [json_name = "comment"];</code>
     *
     * @param value The comment to set.
     * @return This builder for chaining.
     */
    public Builder setComment(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      comment_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string comment = 2 [json_name = "comment"];</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearComment() {
      comment_ = getDefaultInstance().getComment();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string comment = 2 [json_name = "comment"];</code>
     *
     * @param value The bytes for comment to set.
     * @return This builder for chaining.
     */
    public Builder setCommentBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      comment_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:jumpstart.domain.inframanager.values.v1.Approval)
  }

  // @@protoc_insertion_point(class_scope:jumpstart.domain.inframanager.values.v1.Approval)
  private static final io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1
          .Approval
      DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE =
        new io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval();
  }

  public static io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval
      getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Approval> PARSER =
      new com.google.protobuf.AbstractParser<Approval>() {
        @java.lang.Override
        public Approval parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

  public static com.google.protobuf.Parser<Approval> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Approval> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.Approval
      getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
