// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: jumpstart/domain/inframanager/v1/values.proto
// Protobuf Java Version: 4.28.3

package io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1;

/** Protobuf enum {@code jumpstart.domain.inframanager.values.v1.Errors} */
public enum Errors implements com.google.protobuf.ProtocolMessageEnum {
  /** <code>ERRORS_UNSPECIFIED = 0;</code> */
  ERRORS_UNSPECIFIED(0),
  /** <code>ERRORS_INVALID_ARGUMENTS = 1;</code> */
  ERRORS_INVALID_ARGUMENTS(1),
  /** <code>ERRORS_ONBOARD_ENTITY_TIMED_OUT = 2;</code> */
  ERRORS_ONBOARD_ENTITY_TIMED_OUT(2),
  /** <code>ERRORS_SERVICE_UNAVAILABLE = 3;</code> */
  ERRORS_SERVICE_UNAVAILABLE(3),
  /** <code>ERRORS_UNAUTHORIZED = 4;</code> */
  ERRORS_UNAUTHORIZED(4),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        Errors.class.getName());
  }
  /** <code>ERRORS_UNSPECIFIED = 0;</code> */
  public static final int ERRORS_UNSPECIFIED_VALUE = 0;
  /** <code>ERRORS_INVALID_ARGUMENTS = 1;</code> */
  public static final int ERRORS_INVALID_ARGUMENTS_VALUE = 1;
  /** <code>ERRORS_ONBOARD_ENTITY_TIMED_OUT = 2;</code> */
  public static final int ERRORS_ONBOARD_ENTITY_TIMED_OUT_VALUE = 2;
  /** <code>ERRORS_SERVICE_UNAVAILABLE = 3;</code> */
  public static final int ERRORS_SERVICE_UNAVAILABLE_VALUE = 3;
  /** <code>ERRORS_UNAUTHORIZED = 4;</code> */
  public static final int ERRORS_UNAUTHORIZED_VALUE = 4;

  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Errors valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Errors forNumber(int value) {
    switch (value) {
      case 0:
        return ERRORS_UNSPECIFIED;
      case 1:
        return ERRORS_INVALID_ARGUMENTS;
      case 2:
        return ERRORS_ONBOARD_ENTITY_TIMED_OUT;
      case 3:
        return ERRORS_SERVICE_UNAVAILABLE;
      case 4:
        return ERRORS_UNAUTHORIZED;
      default:
        return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Errors> internalGetValueMap() {
    return internalValueMap;
  }

  private static final com.google.protobuf.Internal.EnumLiteMap<Errors> internalValueMap =
      new com.google.protobuf.Internal.EnumLiteMap<Errors>() {
        public Errors findValueByNumber(int number) {
          return Errors.forNumber(number);
        }
      };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }

  public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
    return getDescriptor();
  }

  public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
    return io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1.ValuesProto
        .getDescriptor()
        .getEnumTypes()
        .get(1);
  }

  private static final Errors[] VALUES = values();

  public static Errors valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException("EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Errors(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:jumpstart.domain.inframanager.values.v1.Errors)
}
