// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: jumpstart/domain/inframanager/v1/values.proto
// Protobuf Java Version: 4.28.3

package io.temporal.inframanager.messages.jumpstart.domain.inframanager.values.v1;

public final class ValuesProto {
  private ValuesProto() {}

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        ValuesProto.class.getName());
  }

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_jumpstart_domain_inframanager_values_v1_Approval_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_jumpstart_domain_inframanager_values_v1_Approval_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n-jumpstart/domain/inframanager/v1/value"
          + "s.proto\022\'jumpstart.domain.inframanager.v"
          + "alues.v1\"u\n\010Approval\022O\n\006status\030\001 \001(\01627.j"
          + "umpstart.domain.inframanager.values.v1.A"
          + "pprovalStatusR\006status\022\030\n\007comment\030\002 \001(\tR\007"
          + "comment*\212\001\n\016ApprovalStatus\022\037\n\033APPROVAL_S"
          + "TATUS_UNSPECIFIED\020\000\022\033\n\027APPROVAL_STATUS_P"
          + "ENDING\020\001\022\034\n\030APPROVAL_STATUS_REJECTED\020\002\022\034"
          + "\n\030APPROVAL_STATUS_APPROVED\020\003*\234\001\n\006Errors\022"
          + "\026\n\022ERRORS_UNSPECIFIED\020\000\022\034\n\030ERRORS_INVALI"
          + "D_ARGUMENTS\020\001\022#\n\037ERRORS_ONBOARD_ENTITY_T"
          + "IMED_OUT\020\002\022\036\n\032ERRORS_SERVICE_UNAVAILABLE"
          + "\020\003\022\027\n\023ERRORS_UNAUTHORIZED\020\004B\231\002\nIio.tempo"
          + "ral.inframanager.messages.jumpstart.doma"
          + "in.inframanager.values.v1B\013ValuesProtoP\001"
          + "\242\002\004JDIV\252\002\'Jumpstart.Domain.Inframanager."
          + "Values.V1\312\002\'Jumpstart\\Domain\\Inframanage"
          + "r\\Values\\V1\342\0023Jumpstart\\Domain\\Inframana"
          + "ger\\Values\\V1\\GPBMetadata\352\002+Jumpstart::D"
          + "omain::Inframanager::Values::V1b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {});
    internal_static_jumpstart_domain_inframanager_values_v1_Approval_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_jumpstart_domain_inframanager_values_v1_Approval_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_jumpstart_domain_inframanager_values_v1_Approval_descriptor,
            new java.lang.String[] {
              "Status", "Comment",
            });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
